Repository zcash/zcash, pull requests merged in 2018-10, with the labels that each got.

#3561 Closes #3560. Update Sapling note data correctly when importing a key.
  qa/rpc-tests/wallet_sapling.py
  src/wallet/wallet.cpp
Labels: RPC interface, Sapling, wallet

#3566 For #3546. Shielded tx with missing inputs are not treated as orphans.
  src/main.cpp
Labels: Sapling

#3567 For #3546. Improve estimated tx size for Sapling outputs.
  src/wallet/rpcwallet.cpp
Labels: RPC interface, Sapling

#3450 Fix some typos in rpc-tests readme
  qa/rpc-tests/README.md
Labels: documentation

#3587 Fix HDSeed comment in wallet dump
  qa/rpc-tests/wallet_import_export.py
  src/wallet/rpcdump.cpp
Labels: RPC interface, bug, wallet

#3592 Better error message when sending to both sprout and sapling
  qa/rpc-tests/wallet_sapling.py
  src/wallet/rpcwallet.cpp
Labels: RPC interface, wallet

#3596 For #3359. RPCs return error if Sapling addresses used before Sapling activation.
  qa/rpc-tests/wallet_sapling.py
  src/wallet/rpcwallet.cpp
Labels: wallet

#3599 Update mainnet checkpoint for block 410100.
  src/chainparams.cpp
Labels: consensus protocol, networking

#3601 Update release notes for v2.0.1
  doc/release-notes.md
Labels: Sapling, documentation

#3611 Closes #3467. Add benchmarks for Sapling spends and outputs.
  src/wallet/rpcwallet.cpp
  src/zcbenchmarks.cpp
  src/zcbenchmarks.h
Labels: benchmarking

#3620 Fix error message
  src/wallet/asyncrpcoperation_sendmany.cpp
Labels: Zcash codebase

#3622 Fix potentially misleading test failures
  qa/rpc-tests/test_framework/util.py
Labels: cleanup, testing

#3628 Closes #3329. Send alert to put non-Sapling nodes into safe mode.
  src/sendalert.cpp
Labels: RPC interface, Sapling, alert system, networking

#3627 Closes #3616. Document revoked key error when upgrading on Debian.
  doc/release-notes.md
Labels: documentation
