Repository zcash/zcash, pull requests merged in 2018-04, with the labels that each got.

#3136 Fix z_importviewingkey startHeight parameter
  qa/rpc-tests/wallet_nullifiers.py
  src/wallet/rpcdump.cpp
Labels: RPC interface, bug

#3151 Fix Deprecation test to check for sanitized string from alertnotify.
  src/gtest/test_deprecation.cpp
Labels: testing

#3166 When rewinding, reset pindexBestInvalid if it is pointing to a removed block
  src/main.cpp
Labels: bug, network upgrade management

#3081 Add Sapling to upgrade list
  src/chainparams.cpp
  src/consensus/params.h
  src/consensus/upgrades.cpp
Labels: Sapling wishlist, network upgrade management

#3153 Disable building libzcashconsensus by default
  configure.ac
  zcutil/build.sh
Labels: build, dev policy

#2784 [macOS] added curl download method to fetch-params.sh
  zcutil/fetch-params.sh
Labels: OS X, portability, zkSNARK Parameter Deployment

#3157 Part of #2966, extending Sprout tests to other epochs
  src/gtest/test_validation.cpp
  src/test/DoS_tests.cpp
  src/test/multisig_tests.cpp
  src/test/script_P2SH_tests.cpp
  src/test/script_tests.cpp
Labels: Overwinter, testing

#3175 [fix] proton download path
  depends/packages/proton.mk
Labels: build, dependencies

#3160 Closes #3134 - Least Authority Issue E
  src/test/mempool_tests.cpp
  src/txmempool.h
Labels: LeastAuthority finding, audit task, bug, testing

#3181 Closes #1249 - Least Authority Issue C
  src/crypto/common.h
Labels: LeastAuthority finding, audit task, cleanup

#3074 Add test for dependent txs to mempool_tx_expiry.py
  qa/rpc-tests/mempool_tx_expiry.py
Labels: testing

#3195 Remove now-unshadowed serialization lines that do nothing
  src/alert.h
  src/primitives/block.h
Labels: Bitcoin Core codebase, cleanup

#3205 Return result of boost::apply_visitor
  src/primitives/transaction.cpp
Labels: bug

#2813 Implement uacomment config parameter
  src/init.cpp
  src/main.cpp
  src/net.cpp
  src/net.h
  src/rpcnet.cpp
  src/test/util_tests.cpp
  src/utilstrencodings.cpp
  src/utilstrencodings.h
Labels: Bitcoin Core codebase, networking
