Repository zcash/zcash, pull requests merged in 2018-05, with the labels that each got.

#3220 Implement consensus rules about the number of Spend and Output Descriptions in a transaction
  src/main.cpp
  src/test/transaction_tests.cpp
Labels: consensus protocol

#3179 Add improvements to getblock RPC output
  qa/rpc-tests/merkle_blocks.py
  src/rpcblockchain.cpp
  src/test/rpc_wallet_tests.cpp
Labels: Bitcoin Core codebase, RPC interface, score: 2

#3227 Fix -Wstring-plus-int warning on clang
  src/coins.cpp
  src/test/coins_tests.cpp
  src/txdb.cpp
  src/txmempool.cpp
Labels: OS X, cleanup

#3183 Closes #3182 - Least Authority Issue D
  src/streams.h
Labels: LeastAuthority finding, audit task, cleanup, score: 2

#2894 Make some globals static that can be
  src/asyncrpcoperation.cpp
  src/crypto/equihash.cpp
  src/main.cpp
  src/metrics.cpp
  src/net.cpp
  src/snark/libsnark/common/profiling.cpp
  src/util.cpp
  src/zcash/JoinSplit.cpp
  src/zcash/Proof.cpp
Labels: cleanup

#3201 Clarify help text of dumpprivkey
  src/wallet/rpcdump.cpp
Labels: RPC interface, documentation

#3240 Remove obsolete CreateJoinSplit and GenerateParams binaries
  .gitignore
  qa/zcash/full_test_suite.py
  src/Makefile.am
  src/Makefile.zcash.include
  src/zcash/CreateJoinSplit.cpp
  src/zcash/GenerateParams.cpp
Labels: cleanup

#3264 Update Payment API
  doc/payment-api.md
Labels: documentation

#3271 Switch Rust to 1.26 Stable
  depends/packages/rust.mk
Labels: Rust, dependencies

#3286 Comment out Gitian library handling while we don't build any libraries
  contrib/gitian-descriptors/gitian-linux.yml
  contrib/gitian-descriptors/gitian-win.yml
Labels: build

#3302 Closes #3301. Non-void function should not have empty definition.
  src/zcash/Note.hpp
Labels: bug, review needed

#3287 Add Sapling details to release notes
  doc/release-notes.md
Labels: documentation, release

#3300 Part of #3277. Add comment about deprecated txdb prefixes.
  src/txdb.cpp
Labels: cleanup, documentation
