Repository zcash/zcash, pull requests merged in 2018-02, with the labels that each got.

#2923 Use JoinSplitTestingSetup for Boost sighash tests
  src/test/sighash_tests.cpp
Labels: bug, testing

#2958 Add test to check malformed v1 transaction against Overwinter tx parser
  src/gtest/test_checktransaction.cpp
Labels: testing

#2931 read hashReserved from disk
  src/txdb.cpp
Labels: bug, consensus protocol

#2977 Check Equihash solution when loading block index
  src/txdb.cpp
Labels: error handling

#2968 Fix documentation examples for z_importwallet z_exportwallet exportdir
  doc/wallet-backup.md
  src/wallet/rpcdump.cpp
Labels: RPC interface, cleanup, documentation

#2978 Closes #2964. z_sendmany once again makes v1 tx for taddr to taddr.
  qa/rpc-tests/wallet_overwintertx.py
  src/wallet/asyncrpcoperation_sendmany.cpp
  src/wallet/rpcwallet.cpp
Labels: NU0 wishlist, cleanup, protocol spec, regression, review needed

#2993 Use block hash comparison for consistency check when loading block index
  src/txdb.cpp
Labels: error handling, performance, regression

#3002 Overwinter release notes and testnet activation height
  doc/release-notes.md
  src/chainparams.cpp
Labels: documentation, release
