Repository zcash/zcash, pull requests merged in 2018-11, with the labels that each got.

#3649 Add clarifying text for parameter size
  zcutil/fetch-params.sh
Labels: documentation

#3631 rename HaveJoinSplitRequirements for Sapling
  src/coins.cpp
  src/coins.h
  src/main.cpp
  src/test/coins_tests.cpp
Labels: Sapling, cleanup

#3637 Update COPYRIGHT_YEAR from 2017 to 2018
  configure.ac
Labels: cleanup, licensing

#3613 Closes #3597. TransactionBuilder should check tx version before adding Sapling spends and outputs
  src/gtest/test_transaction_builder.cpp
  src/transaction_builder.cpp
Labels: Sapling, Zcash codebase

#3585 Update IncrementalMerkleTree test vectors to use valid commitments
  src/test/data/merkle_commitments_sapling.json
  src/test/data/merkle_path_sapling.json
  src/test/data/merkle_roots_sapling.json
  src/test/data/merkle_serialization_sapling.json
  src/test/data/merkle_witness_serialization_sapling.json
Labels: Sapling, testing

#3663 Cleaning up RPC output
  src/wallet/rpcwallet.cpp
Labels: RPC interface, documentation, user interface

#2815 Relay blocks when pruning
  src/main.cpp
Labels: Bitcoin Core codebase, networking

#3670 don't ban peers when loading pre-sapling (and pre-blossom) blocks
  src/gtest/test_checkblock.cpp
  src/main.cpp
Labels: networking

#3697 remove non-ascii characters from help text
  src/wallet/rpcwallet.cpp
Labels: RPC interface
