Repository zcash/zcash, pull requests merged in 2018-03, with the labels that each got.

#3027 Fix typos in various files
  .github/ISSUE_TEMPLATE.md
  doc/payment-api.md
  doc/security-warnings.md
  doc/zmq.md
  src/addrman.h
  src/asyncrpcoperation.h
  src/base58.h
  src/coins.h
  src/consensus/params.h
  src/gtest/test_mempool.cpp
  src/httprpc.cpp
  src/init.cpp
  src/main.cpp
  src/merkleblock.cpp
  src/merkleblock.h
  src/miner.cpp
  src/net.cpp
  src/netbase.cpp
  src/netbase.h
  src/policy/fees.h
  src/pow/tromp/equi_miner.h
  src/rest.cpp
  src/rpcblockchain.cpp
  src/rpcnet.cpp
  src/rpcrawtransaction.cpp
  src/script/interpreter.cpp
  src/script/script.cpp
  src/script/sigcache.cpp
  src/script/sign.h
  src/snark/README.md
  src/snark/libsnark/algebra/evaluation_domain/evaluation_domain.hpp
  src/snark/libsnark/algebra/fields/bigint.hpp
  src/snark/libsnark/algebra/fields/bigint.tcc
  src/snark/libsnark/algebra/fields/fp.hpp
  src/snark/libsnark/algebra/scalar_multiplication/kc_multiexp.hpp
  src/snark/libsnark/common/data_structures/sparse_vector.hpp
  src/snark/libsnark/common/profiling.cpp
  src/snark/libsnark/common/serialization.hpp
  src/snark/libsnark/reductions/r1cs_to_qap/r1cs_to_qap.hpp
  src/snark/libsnark/relations/variable.hpp
  src/snark/libsnark/zk_proof_systems/ppzksnark/r1cs_ppzksnark/r1cs_ppzksnark.hpp
  src/snark/libsnark/zk_proof_systems/ppzksnark/r1cs_ppzksnark/r1cs_ppzksnark.tcc
  src/support/pagelocker.h
  src/test/addrman_tests.cpp
  src/test/miner_tests.cpp
  src/test/rpc_tests.cpp
  src/tinyformat.h
  src/torcontrol.cpp
  src/univalue/lib/univalue.cpp
  src/wallet/asyncrpcoperation_sendmany.cpp
  src/wallet/gtest/test_wallet.cpp
  src/wallet/rpcwallet.cpp
  src/wallet/wallet.h
Labels: cleanup

#3036 Fix typo in comment: should link to issue #1359.
  src/wallet/asyncrpcoperation_mergetoaddress.cpp
Labels: cleanup

#3050 Code clean up. Remove use of X macro.
  src/net.cpp
Labels: Bitcoin Core codebase, cleanup, networking, review needed

#3079 pyflakes cleanups to RPC tests after Overwinter PRs.
  qa/rpc-tests/mempool_tx_expiry.py
  qa/rpc-tests/overwinter_peer_management.py
  qa/rpc-tests/reorg_limit.py
  qa/rpc-tests/wallet_mergetoaddress.py
  qa/rpc-tests/wallet_overwintertx.py
Labels: cleanup

#3089 [macOS] Fix test/gtest bugs caught by latest clang
  src/gtest/test_deprecation.cpp
  src/test/rpc_wallet_tests.cpp
Labels: OS X, portability, testing

#3069 Disable auto-deprecation on regtest and testnet
  src/deprecation.cpp
  src/gtest/test_deprecation.cpp
Labels: auto-senescence, bug, testing, testnet

#3093 Remove local function wait_and_assert_operationid_status which is now defined in test framework
  qa/rpc-tests/wallet_protectcoinbase.py
  qa/rpc-tests/zkey_import_export.py
Labels: cleanup, simplification, testing

#3091 Closes #1988. Add qa test for cache invalidation bug found in v1.0.0 to v1.0.3.
  qa/pull-tester/rpc-tests.sh
  qa/rpc-tests/wallet_anchorfork.py
Labels: SECURITY, testing

#3077 Split declaration and definition of SPROUT_BRANCH_ID constant
  src/consensus/upgrades.cpp
  src/consensus/upgrades.h
Labels: bug, portability

#3082 Add link to Overwinter info page
  src/consensus/upgrades.cpp
Labels: documentation, network upgrade management, usability, user interface

#3120 cleanup: Ensure code is pyflakes-clean for CI
  qa/rpc-tests/wallet_anchorfork.py
  qa/rpc-tests/zkey_import_export.py
  qa/zcash/create_benchmark_archive.py
  src/test/bctest.py
  zcutil/release-notes.py
Labels: cleanup

#3111 Closes #3110. Ensure user can see error message about absurdly high fees.
  qa/rpc-tests/wallet.py
  src/main.cpp
Labels: RPC interface, error handling, wallet

#3109 Part of #2966, extending Sprout tests to other epochs.
  src/test/transaction_tests.cpp
Labels: review needed, testing

#3117 Add filename and SHA256 hash for Windows Rust package
  depends/packages/rust.mk
Labels: Rust, dependencies

#3096 depends: Explicitly download and vendor Rust dependencies
  depends/Makefile
  depends/cargo-checksum.sh
  depends/funcs.mk
  depends/packages/crate_libc.mk
  depends/packages/librustzcash.mk
  depends/packages/packages.mk
  depends/patches/librustzcash/cargo.config
Labels: Rust, build, dependencies, review needed

#3124 Update boost package URL to match official download url on boost.org
  depends/packages/boost.mk
Labels: build, dependencies

#2913 Closes #2910. Add z_listunspent RPC call.
  qa/rpc-tests/wallet_protectcoinbase.py
  src/rpcclient.cpp
  src/rpcserver.cpp
  src/rpcserver.h
  src/test/rpc_wallet_tests.cpp
  src/wallet/rpcwallet.cpp
  src/wallet/wallet.cpp
  src/wallet/wallet.h
Labels: RPC interface, wallet

#3130 Upgrade OpenSSL to 1.1.0h
  depends/packages/openssl.mk
Labels: SECURITY, dependencies

#3127 Make Rust compilation mandatory
  configure.ac
  depends/Makefile
  src/pow.cpp
  zcutil/build.sh
Labels: Rust, Sapling wishlist, build, dependencies, dev policy, portability, review needed

#3106 Add Note Locking to z_mergetoaddress
  qa/rpc-tests/wallet_mergetoaddress.py
  src/wallet/asyncrpcoperation_mergetoaddress.cpp
  src/wallet/asyncrpcoperation_mergetoaddress.h
  src/wallet/gtest/test_wallet.cpp
  src/wallet/wallet.cpp
  src/wallet/wallet.h
Labels: RPC interface, bug, performance
