Repository zcash/zcash, pull requests merged in 2019-07, with the labels that each got.

#4052 Rename vjoinsplit to vJoinSplit
  qa/rpc-tests/test_framework/mininode.py
  src/coins.cpp
  src/gtest/test_checktransaction.cpp
  src/gtest/test_mempool.cpp
  src/gtest/test_transaction_builder.cpp
  src/main.cpp
  src/miner.cpp
  src/primitives/transaction.cpp
  src/primitives/transaction.h
  src/rpc/rawtransaction.cpp
  src/script/interpreter.cpp
  src/test/coins_tests.cpp
  src/test/sighash_tests.cpp
  src/test/transaction_tests.cpp
  src/transaction_builder.cpp
  src/txmempool.cpp
  src/utiltest.cpp
  src/wallet/asyncrpcoperation_mergetoaddress.cpp
  src/wallet/asyncrpcoperation_saplingmigration.cpp
  src/wallet/asyncrpcoperation_sendmany.cpp
  src/wallet/asyncrpcoperation_shieldcoinbase.cpp
  src/wallet/gtest/test_wallet.cpp
  src/wallet/paymentdisclosure.h
  src/wallet/rpcdisclosure.cpp
  src/wallet/rpcwallet.cpp
  src/wallet/wallet.cpp
  src/wallet/wallet.h
Labels: cleanup, community contribution

#4055 Rename FindWalletTx to FindWalletTxToZap
  src/wallet/walletdb.cpp
  src/wallet/walletdb.h
Labels: cleanup, community contribution

#4054 Rename joinsplit to shielded
  src/main.cpp
Labels: cleanup, community contribution

#4053 Fix naming inconsistency
  src/wallet/rpcwallet.cpp
Labels: community contribution, documentation

#4044 Fix comment in mergetoaddress RPC test
  qa/rpc-tests/mergetoaddress_helper.py
Labels: cleanup

#3927 Handful of copyedits to README.md
  README.md
Labels: cleanup, community contribution, documentation

#4075 Fix nondeterministic failure in sapling migration test
  qa/rpc-tests/sprout_sapling_migration.py
Labels: tech_debt, testing

#4056 Fix RPC undefined behavior
  src/arith_uint256.cpp
Labels: SECURITY, bug, community contribution

#4082 Release process doc: add step to set the gpg key id
  doc/release-process.md
Labels: documentation, release
