Repository zcash/zcash, pull requests merged in 2019-08, with the labels that each got.

#3926 add addressindex RPC for bitcore block explorer
  qa/pull-tester/rpc-tests.sh
  qa/rpc-tests/addressindex.py
  src/addressindex.h
  src/main.cpp
  src/main.h
  src/rpc/client.cpp
  src/rpc/misc.cpp
  src/rpc/rawtransaction.cpp
  src/script/script.cpp
  src/script/standard.cpp
  src/script/standard.h
  src/test/rpc_tests.cpp
  src/test/rpc_wallet_tests.cpp
  src/test/test_bitcoin.h
  src/txdb.cpp
  src/txmempool.cpp
  src/txmempool.h
Labels: explorer, needs documentation, operations, packaging

#3953 add getspent RPCs for bitcore block explorer
  qa/pull-tester/rpc-tests.sh
  qa/rpc-tests/addressindex.py
  qa/rpc-tests/getrawtransaction_insight.py
  qa/rpc-tests/spentindex.py
  src/main.cpp
  src/rpc/blockchain.cpp
  src/rpc/client.cpp
  src/rpc/misc.cpp
  src/rpc/rawtransaction.cpp
  src/test/rpc_tests.cpp
  src/txmempool.cpp
  src/txmempool.h
Labels: explorer, needs documentation, operations, packaging

#4098 Improve caching on parameter downloads
  zcutil/fetch-params.sh
Labels: zkSNARK Parameter Deployment

#4110 Update INSTALL
  INSTALL
Labels: community contribution, documentation

#4120 Add intended rewind for Blossom on testnet
  src/main.cpp
Labels: testnet

#4115 #4114 Don't call GetSpentIndex() when converting txs to JSON if spent index is disabled
  src/main.cpp
  src/rpc/rawtransaction.cpp
Labels: explorer, logging
