Repository zcash/zcash, pull requests merged in 2019-04, with the labels that each got.

#3907 fix enable-debug build DB_COINS undefined
  src/zcbenchmarks.cpp
Labels: bug, build, macOS, usi

#3906 Update _COPYRIGHT_YEAR in configure.ac to 2019
  configure.ac
Labels: cleanup, community contribution, licensing

#3935 Add Blossom to upgrade list
  src/chainparams.cpp
  src/consensus/params.h
  src/consensus/upgrades.cpp
Labels: Blossom

#3901 Update "Zcash Company" to "Electric Coin Company"
  code_of_conduct.md
  contrib/debian/control
  contrib/debian/copyright
  zcutil/make-release.py
Labels: cleanup, community contribution

#3948 Create a checklist for all zcash PRs
  .github/pull_request_template.md
Labels: dev policy

#3951 Update boost to v1.70.0 to eliminate build warning
  depends/packages/boost.mk
Labels: 2.0.6 wishlist, build, dependencies

#3940 init: Fix new HD seed generation for previously-encrypted wallets
  src/init.cpp
  src/wallet/wallet.cpp
Labels: bug, wallet

#3849 add SpentIndex changes needed for bitcore block explorer
  src/Makefile.am
  src/main.cpp
  src/main.h
  src/script/script.cpp
  src/spentindex.h
  src/txdb.cpp
  src/txdb.h
Labels: explorer, needs documentation, operations, packaging

#3857 add TimestampIndex changes needed for bitcore block explorer
  src/Makefile.am
  src/main.cpp
  src/main.h
  src/timestampindex.h
  src/txdb.cpp
  src/txdb.h
Labels: explorer, needs documentation, operations, packaging
