Repository zcash/zcash, pull requests merged in 2019-12, with the labels that each got.

#4165 Remove CheckProofOfWork errors from logs
  src/main.cpp
  src/pow.cpp
Labels: community contribution

#4168 change LoadKeyMetadata, LoadZKeyMetadata and LoadSaplingZKeyMetadata to void
  src/wallet/gtest/test_wallet_zkeys.cpp
  src/wallet/wallet.cpp
  src/wallet/wallet.h
Labels: community contribution

#4180 Add node version to metrics screen
  src/metrics.cpp
Labels: community contribution

#4211 Remove option mempooltxinputlimit
  qa/rpc-tests/mergetoaddress_helper.py
  src/gtest/test_mempool.cpp
  src/init.cpp
  src/main.cpp
  src/test/rpc_wallet_tests.cpp
  src/wallet/asyncrpcoperation_mergetoaddress.cpp
  src/wallet/asyncrpcoperation_sendmany.cpp
  src/wallet/asyncrpcoperation_shieldcoinbase.cpp
  src/wallet/rpcwallet.cpp
  src/wallet/wallet.cpp
Labels: cleanup, community contribution

#4221 Fix typo
  qa/rpc-tests/wallet_addresses.py
Labels: cleanup, community contribution, documentation, testing

#4240 Add Heartwood to upgrade list
  src/chainparams.cpp
  src/consensus/params.h
  src/consensus/upgrades.cpp
Labels: network upgrade management

#4176 avoid blockchain progress greater than 1.0
  src/checkpoints.cpp
Labels: community contribution

#4261 Add z_mergetoaddress to release notes
  doc/release-notes.md
Labels: RPC interface, documentation
