Repository zcash/zcash, pull requests merged in 2019-09, with the labels that each got.

#4088 insightexplorer: formatting, pyflakes cleanups
  qa/rpc-tests/addressindex.py
  qa/rpc-tests/spentindex.py
  src/rpc/misc.cpp
Labels: explorer, needs documentation, operations, packaging

#3866 Adding hash for complete IPFS params
  zcutil/fetch-params.sh
Labels: Sapling, community contribution, zkSNARK Parameter Deployment

#4130 Change Debian package description
  contrib/debian/control
Labels: Linux, packaging
