Repository zcash/zcash, pull requests merged in 2019-11, with the labels that each got.

#4161 remove duplicated prefix in errors and warnings
  src/init.cpp
Labels: community contribution

#4182 Minor tweak to the README.md file
  README.md
Labels: community contribution

#4212 Fix CVE-2017-18350
  src/netbase.cpp
Labels: Bitcoin Core codebase, SECURITY

#4216 Cast uint8* in InterruptibleRecv to char* for recv
  src/netbase.cpp
Labels: Windows, bug, portability
