Repository zcash/zcash, pull requests merged in 2019-03, with the labels that each got.

#3887 Update chain work and checkpoint for 2.0.4
  src/chainparams.cpp
Labels: release

#3846 Correcting logo on README
  doc/imgs/logo.png
Labels: documentation

#3839 Update of copyright year to 2019
  COPYING
  contrib/debian/copyright
Labels: licensing

#3897 Check consistency of note commitment and ciphertext in wallet
  src/utiltest.cpp
  src/utiltest.h
  src/wallet/gtest/test_wallet.cpp
  src/wallet/wallet.cpp
Labels: SECURITY

#3900 Update release notes for 2.0.4
  doc/release-notes.md
Labels: documentation, release

#3898 Update COPYRIGHT_YEAR in clientversion.h to 2019
  src/clientversion.h
Labels: cleanup

#3919 Fix OpenSSL reproducible build regression
  depends/packages/openssl.mk
Labels: dependencies, review needed

#3902 Minor spelling changes
  responsible_disclosure.md
Labels: documentation
