Repository zcash/zcash, pull requests merged in 2020-04, with the labels that each got.

#4411 Backport RPC test harness PRs
  Makefile.am
  qa/pull-tester/rpc-tests.sh
  qa/pull-tester/run-bitcoin-cli
  qa/rpc-tests/getblocktemplate_longpoll.py
  qa/rpc-tests/rpcbind_test.py
  qa/rpc-tests/test_framework/authproxy.py
  qa/rpc-tests/test_framework/coverage.py
  qa/rpc-tests/test_framework/test_framework.py
  qa/rpc-tests/test_framework/util.py
Labels: Bitcoin Core codebase, scratching an itch, testing

#4422 depends: Fix OpenSSL download path
  depends/packages/openssl.mk
Labels: dependencies

#4371 Check failing transparent and JoinSplit signatures against the previous network upgrade
  src/consensus/upgrades.cpp
  src/consensus/upgrades.h
  src/gtest/test_checktransaction.cpp
  src/gtest/test_mempool.cpp
  src/gtest/test_validation.cpp
  src/main.cpp
  src/transaction_builder.cpp
  src/transaction_builder.h
Labels: consensus protocol, error handling, scratching an itch, usability

#4424 multiple debug categories documentation
  src/init.cpp
Labels: documentation

#4430 Rust build fixes
  qa/zcash/full_test_suite.py
  src/Makefile.am
Labels: ARM, Rust, Windows, bug, build, librustzcash, macOS, portability

#4426 Return address info in z_importviewingkey
  qa/rpc-tests/wallet_nullifiers.py
  qa/rpc-tests/wallet_sapling.py
  src/wallet/rpcdump.cpp
  src/zcash/Address.cpp
  src/zcash/Address.hpp
Labels: RPC interface

#4434 Remove stale comment about soft-fork upgrades
  src/main.cpp
Labels: Bitcoin design divergence, cleanup

#4402 Add -lightwalletd experimental option
  qa/rpc-tests/addressindex.py
  src/experimental_features.cpp
  src/experimental_features.h
  src/gtest/test_rpc.cpp
  src/init.cpp
  src/main.cpp
  src/rpc/blockchain.cpp
  src/rpc/misc.cpp
  src/rpc/server.cpp
  src/rpc/server.h
  src/wallet/rpcdisclosure.cpp
  src/wallet/rpcwallet.cpp
Labels: RPC interface, light clients

#4435 Point at support community on Discord
  README.md
Labels: documentation

#4446 Heisenbug squashing
  qa/rpc-tests/addressindex.py
  src/wallet/gtest/test_wallet.cpp
Labels: heisenbug, testing

#4264 [ZIP 221] FlyClient - Consensus-Layer Changes
  qa/pull-tester/rpc-tests.sh
  qa/rpc-tests/feature_zip221.py
  qa/rpc-tests/test_framework/flyclient.py
  qa/rpc-tests/test_framework/mininode.py
  src/Makefile.am
  src/Makefile.gtest.include
  src/chain.h
  src/coins.cpp
  src/coins.h
  src/gtest/test_history.cpp
  src/main.cpp
  src/miner.cpp
  src/primitives/block.cpp
  src/primitives/block.h
  src/rpc/blockchain.cpp
  src/rpc/mining.cpp
  src/rust/include/librustzcash.h
  src/rust/src/rustzcash.rs
  src/test/coins_tests.cpp
  src/test/miner_tests.cpp
  src/txdb.cpp
  src/txdb.h
  src/zcash/History.cpp
  src/zcash/History.hpp
Labels: committed

#4448 consensus: From Heartwood activation, use Rust Equihash validator
  src/main.cpp
  src/main.h
  src/pow.cpp
  src/pow.h
  src/test/equihash_tests.cpp
  src/zcbenchmarks.cpp
Labels: PoW and mining, consensus protocol

#4410 Add `zcutil/clean.sh` and `zcutil/distclean.sh` scripts that work reliably (unlike `make clean`)
  zcutil/clean.sh
  zcutil/distclean.sh
Labels: build

#4450 Updates to zcutil/make-release.py
  zcutil/make-release.py
  zcutil/release-notes.py
Labels: Automation, Python, bug, release

#4306 Compute more structures in CTxMemPool::DynamicMemoryUsage()
  src/memusage.h
  src/txmempool.cpp
Labels: Mempool, bug, memory management

#4416 Use SA_RESTART in sa_flags when setting up signal handlers
  src/init.cpp
Labels: scratching an itch

#4452 Fix typos in test framework
  qa/rpc-tests/test_framework/util.py
Labels: cleanup, testing

#4453 Update release notes for v2.1.2
  doc/release-notes.md
Labels: documentation, release

#4457 Release v2.1.2-rc1
  README.md
  configure.ac
  contrib/debian/changelog
  contrib/gitian-descriptors/gitian-linux.yml
  doc/man/zcash-cli.1
  doc/man/zcash-tx.1
  doc/man/zcashd.1
  doc/release-notes/release-notes-2.1.2-rc1.md
  src/chain.h
  src/clientversion.h
  src/deprecation.h
  src/main.cpp
Labels: release

#4468 Set Heartwood activation height for testnet to 903800.
  doc/release-notes.md
  src/chainparams.cpp
  src/net.h
  src/version.h
Labels: consensus protocol, testnet

#4249 Add confirmations, blockheight, blockindex and blocktime to z_listreceivedbyaddress
  qa/rpc-tests/wallet_listreceived.py
  qa/rpc-tests/wallet_nullifiers.py
  src/wallet/rpcwallet.cpp
Labels: RPC interface, committed

#4462 Fix typos
  build-aux/m4/ax_boost_base.m4
  build-aux/m4/ax_gcc_func_attribute.m4
  zcutil/make-release.py
Labels: cleanup

#4427 Remove option to load new blocks from ConnectTip
  src/main.cpp
Labels: cleanup, committed

#4465 Add z_getnotescount API
  qa/rpc-tests/wallet_listreceived.py
  src/rpc/client.cpp
  src/wallet/rpcwallet.cpp
Labels: RPC interface, wallet
