Repository zcash/zcash, pull requests merged in 2020-09, with the labels that each got.

#4702 Release v4.0.0
  README.md
  configure.ac
  contrib/debian/changelog
  contrib/gitian-descriptors/gitian-linux.yml
  doc/authors.md
  doc/man/zcash-cli.1
  doc/man/zcash-tx.1
  doc/man/zcashd.1
  doc/release-notes.md
  doc/release-notes/release-notes-4.0.0.md
  qa/zcash/postponed-updates.txt
  src/chainparams.cpp
  src/clientversion.h
  src/deprecation.h
  src/version.h
Labels: A-consensus, release

#4688 Add a missing % to a string interpolation in rpc test framework
  qa/rpc-tests/test_framework/mininode.py
Labels: C-cleanup

#2778 Add assert_raises_message to the python test framework.
  qa/rpc-tests/test_framework/authproxy.py
  qa/rpc-tests/test_framework/util.py
Labels: A-testing, C-cleanup, PR_cleanup, spring_cleaning

#4349 Prevent creation of shielded transactions when chain is not synced up
  src/rpc/blockchain.cpp
  src/wallet/rpcwallet.cpp
Labels: A-chain-sync, A-rpc-interface, A-wallet

#4357 Add null check to feof
  src/streams.h
Labels: C-bug

#4687 Fix buffer overflows in P2PKH tests
  src/test/script_P2PKH_tests.cpp
Labels: C-cleanup

#4561 Allow full and relative path wallet database location
  qa/pull-tester/rpc-tests.sh
  qa/rpc-tests/feature_walletfile.py
  src/wallet/wallet.cpp
Labels: A-wallet

#4706 Allow multiple nuparams options in config file
  src/util.cpp
Labels: A-testing, usability, use case

#4732 Postponed dependency updates, refer to core team sync meeting.
  qa/zcash/postponed-updates.txt
Labels: A-dependencies

#4696 wallet: Add ANY_TADDR special string to z_sendmany
  qa/pull-tester/rpc-tests.sh
  qa/rpc-tests/wallet_sendmany_any_taddr.py
  src/wallet/asyncrpcoperation_sendmany.cpp
  src/wallet/asyncrpcoperation_sendmany.h
  src/wallet/rpcwallet.cpp
Labels: A-rpc-interface, A-wallet, use case

#4720 Address some performance regressions
  Cargo.lock
  Cargo.toml
  depends/packages/native_rust.mk
  qa/zcash/postponed-updates.txt
  rust-toolchain
Labels: A-dependencies, I-performance

#4693 Make some conversions explicit to reduce sanitizer warnings
  src/chain.h
  src/secp256k1/src/scalar_4x64_impl.h
  src/zcash/util.cpp
Labels: C-cleanup, S-scratching-an-itch

#4690 Flush witness data when consistent (part 2)
  src/chainparams.cpp
  src/init.cpp
  src/main.h
  src/validationinterface.cpp
  src/validationinterface.h
  src/wallet/wallet.cpp
  src/wallet/wallet.h
Labels: A-wallet-database, C-bug

#4743 depends: Remove cargo-checksum.sh
  depends/cargo-checksum.sh
Labels: A-dependencies, C-cleanup

#4746 build: Remove Rust staticlib naming workaround
  src/Makefile.am
Labels: A-build, C-bug, O-windows

#4734 Replace libsodium BLAKE2b usage with blake2b_simd crate
  Cargo.lock
  Cargo.toml
  src/Makefile.am
  src/crypto/equihash.cpp
  src/crypto/equihash.h
  src/gtest/test_equihash.cpp
  src/hash.h
  src/miner.cpp
  src/pow/tromp/equi.h
  src/pow/tromp/equi_miner.h
  src/rpc/mining.cpp
  src/rust/include/rust/blake2b.h
  src/rust/include/tracing.h
  src/rust/src/blake2b.rs
  src/rust/src/rustzcash.rs
  src/script/interpreter.cpp
  src/test/equihash_tests.cpp
  src/test/miner_tests.cpp
  src/test/test_bitcoin.cpp
  src/zcash/JoinSplit.cpp
  src/zcash/NoteEncryption.cpp
  src/zcash/address/sapling.cpp
  src/zcash/address/zip32.cpp
  src/zcash/prf.cpp
  src/zcbenchmarks.cpp
Labels: A-dependencies, C-cleanup, L-rust

#4558 [RPC] Add transaction size to JSON output
  src/rpc/rawtransaction.cpp
  src/test/rpc_tests.cpp
Labels: A-rpc-interface, C-upstream-port

#4749 depends: Update to latest config.guess & config.sub
  Makefile.am
  contrib/gitian-descriptors/gitian-linux.yml
  depends/config.guess
  depends/config.sub
  depends/packages/native_rust.mk
  qa/zcash/full_test_suite.py
Labels: A-build, A-dependencies

#4643 Locked memory manager
  src/Makefile.am
  src/Makefile.bench.include
  src/Makefile.gtest.include
  src/bench/lockedpool.cpp
  src/gtest/test_allocator.cpp
  src/hash.h
  src/init.cpp
  src/key.cpp
  src/key.h
  src/pubkey.h
  src/rpc/misc.cpp
  src/support/allocators/secure.h
  src/support/lockedpool.cpp
  src/support/lockedpool.h
  src/support/pagelocker.cpp
  src/support/pagelocker.h
  src/test/allocator_tests.cpp
  src/uint256.h
  src/wallet/crypter.cpp
  src/wallet/crypter.h
  src/wallet/test/crypto_tests.cpp
Labels: C-upstream-port, I-SECURITY, memory management
