Repository zcash/zcash, pull requests merged in 2020-11, with the labels that each got.

#4835 bitcoin-util-test.py backports
  src/test/README.md
  src/test/bctest.py
  src/test/bitcoin-util-test.py
  src/test/data/bitcoin-util-test.json
  src/test/data/blanktx.json
  src/test/data/tt-delin1-out.json
  src/test/data/tt-delout1-out.json
  src/test/data/tt-locktime317000-out.json
  src/test/data/txcreate1.json
  src/test/data/txcreate2.json
  src/test/data/txcreatedata_seq0.json
  src/test/data/txcreatedata_seq1.json
  src/test/data/txcreatesign.json
Labels: A-testing, C-upstream-port

#4829 Backport useful lints from upstream
  contrib/devtools/gen-manpages.sh
  contrib/devtools/test-security-check.py
  contrib/gitian-descriptors/gitian-linux.yml
  contrib/gitian-descriptors/gitian-osx-signer.yml
  contrib/gitian-descriptors/gitian-osx.yml
  contrib/gitian-descriptors/gitian-win.yml
  contrib/linearize/linearize-data.py
  contrib/linearize/linearize-hashes.py
  contrib/qos/tc.sh
  contrib/seeds/generate-seeds.py
  doc/developer-notes.md
  src/bench/bench.cpp
  src/bench/perf.h
  src/key_io.h
  src/policy/fees.h
  src/policy/policy.h
  src/prevector.h
  src/rpc/client.h
  src/rpc/protocol.h
  src/rpc/register.h
  src/rpc/server.h
  src/wallet/test/wallet_test_fixture.h
  test/lint/README.md
  test/lint/lint-all.sh
  test/lint/lint-include-guards.sh
  test/lint/lint-includes.sh
  test/lint/lint-locale-dependence.sh
  test/lint/lint-python-utf8-encoding.sh
  test/lint/lint-shebang.sh
  test/lint/lint-shell-locale.sh
  test/lint/lint-shell.sh
  test/lint/lint-whitespace.sh
Labels: A-CI, C-upstream-port

#4574 Add blockhash parameter to getrawtransaction
  qa/rpc-tests/rawtransactions.py
  src/main.cpp
  src/main.h
  src/rpc/rawtransaction.cpp
Labels: A-rpc-interface, C-upstream-port

#4851 Don't compile ehHashState::* if mining is disabled
  src/crypto/equihash.cpp
Labels: A-pow

#4852 Update Rust dependencies
  Cargo.lock
Labels: A-dependencies

#4865 Correctly report founder's reward amount in getblocktemplate prior to Canopy
  src/rpc/mining.cpp
Labels: A-rpc-interface

#4864 Set release CFLAGS/CXXFLAGS to use -O3.
  depends/hosts/darwin.mk
  depends/hosts/freebsd.mk
  depends/hosts/linux.mk
  depends/hosts/mingw32.mk
Labels: A-build, I-performance, safe-to-build

#4869 Release v4.1.1
  README.md
  configure.ac
  contrib/debian/changelog
  contrib/gitian-descriptors/gitian-linux.yml
  doc/authors.md
  doc/man/zcash-cli.1
  doc/man/zcash-tx.1
  doc/man/zcashd.1
  doc/release-notes/release-notes-4.1.1.md
  src/clientversion.h
  src/deprecation.h
Labels: release, safe-to-build

#4868 Windows cross-build generates .lib files, which should be ignored by git and removed by clean
  .gitignore
  src/Makefile.am
  zcutil/clean.sh
Labels: A-build

#4871 Fix typo
  src/zcbenchmarks.cpp
Labels: C-cleanup

#4870 Update expected fails for Sprout txns flows on Canopy
  qa/zcash/smoke_tests.py
Labels: A-testing, safe-to-build

#4843 Improving asyncOp_sendmany redundancies (first round)
  qa/rpc-tests/wallet_shieldingcoinbase.py
  src/wallet/asyncrpcoperation_sendmany.cpp
  src/wallet/asyncrpcoperation_sendmany.h
  src/wallet/test/rpc_wallet_tests.cpp
  src/wallet/wallet.cpp
  src/wallet/wallet.h
Labels: A-rpc-interface, A-wallet, C-cleanup

#4873 Enable mininodes to construct blocks in RPC tests
  qa/rpc-tests/test_framework/blocktools.py
  qa/rpc-tests/test_framework/script.py
  src/chainparams.cpp
  src/chainparams.h
  src/consensus/params.h
  src/pow.cpp
  src/utiltest.cpp
Labels: A-testing, C-upstream-port, S-scratching-an-itch

#4793 test: Use default shielded address in RPC tests where the type is irrelevant
  qa/rpc-tests/regtest_signrawtransaction.py
  qa/rpc-tests/wallet.py
  qa/rpc-tests/wallet_1941.py
  qa/rpc-tests/wallet_anchorfork.py
  qa/rpc-tests/wallet_changeindicator.py
  qa/rpc-tests/wallet_nullifiers.py
  qa/rpc-tests/wallet_treestate.py
  qa/rpc-tests/zkey_import_export.py
Labels: A-CI, A-testing

#4553 Return address in z_importviewingkey error
  src/wallet/rpcdump.cpp
Labels: A-rpc-interface

#4745 configure.ac: Introduce macros to simplify requiring tools.
  configure.ac
Labels: A-build
