Repository zcash/zcash, pull requests merged in 2020-10, with the labels that each got.

#4740 Remove OpenSSL
  COPYING
  configure.ac
  contrib/debian/copyright
  contrib/docker/README.md
  depends/packages/openssl.mk
  depends/packages/packages.mk
  doc/man/zcash-cli.1
  doc/man/zcash-tx.1
  doc/man/zcashd.1
  libzcashconsensus.pc.in
  qa/zcash/postponed-updates.txt
  qa/zcash/updatecheck.py
  src/Makefile.am
  src/Makefile.bench.include
  src/Makefile.gtest.include
  src/Makefile.test.include
  src/init.cpp
  src/key.h
  src/script/script.h
  src/test/bignum.h
  src/test/crypto_tests.cpp
  src/test/sanity_tests.cpp
  src/test/scriptnum10.h
  src/test/scriptnum_tests.cpp
  src/util.cpp
  src/wallet/test/crypto_tests.cpp
Labels: A-dependencies, C-upstream-port

#4756 build: Remove a stray -lcrypto
  configure.ac
Labels: A-build, C-bug, O-macos, portability

#4752 Small httpserver.cpp backports
  qa/rpc-tests/httpbasics.py
  src/httpserver.cpp
  src/httpserver.h
  src/init.cpp
  src/main.cpp
  src/miner.cpp
  src/ui_interface.h
Labels: A-rpc-interface, C-upstream-port, S-scratching-an-itch

#4484 Fix undefined behavior in the test_bitcoin tests
  src/consensus/params.h
  src/wallet/test/rpc_wallet_tests.cpp
Labels: A-testing, C-bug

#4758 Update dependencies
  depends/Makefile
  depends/packages/googletest.mk
  depends/packages/libevent.mk
  depends/packages/native_ccache.mk
  depends/packages/utfcpp.mk
  depends/patches/libevent/detect-arch4random_addrandom-fix.patch
  depends/patches/libevent/detect-arch4random_addrandom.patch
  qa/zcash/postponed-updates.txt
Labels: A-dependencies

#4762 Remove deprecated init.md
  doc/init.md
Labels: C-cleanup

#4763 Remove Bitcoin release notes
  doc/bitcoin-release-notes/release-notes-0.10.0.md
  doc/bitcoin-release-notes/release-notes-0.10.1.md
  doc/bitcoin-release-notes/release-notes-0.10.2.md
  doc/bitcoin-release-notes/release-notes-0.10.3.md
  doc/bitcoin-release-notes/release-notes-0.11.1.md
  doc/bitcoin-release-notes/release-notes-0.11.2.md
  doc/bitcoin-release-notes/release-notes-0.3.12.md
  doc/bitcoin-release-notes/release-notes-0.3.13.md
  doc/bitcoin-release-notes/release-notes-0.3.14.md
  doc/bitcoin-release-notes/release-notes-0.3.15.md
  doc/bitcoin-release-notes/release-notes-0.3.16.md
  doc/bitcoin-release-notes/release-notes-0.3.17.md
  doc/bitcoin-release-notes/release-notes-0.3.18.md
  doc/bitcoin-release-notes/release-notes-0.3.19.md
  doc/bitcoin-release-notes/release-notes-0.3.20.1.md
  doc/bitcoin-release-notes/release-notes-0.3.20.2.md
  doc/bitcoin-release-notes/release-notes-0.3.20.md
  doc/bitcoin-release-notes/release-notes-0.3.21.md
  doc/bitcoin-release-notes/release-notes-0.3.22.md
  doc/bitcoin-release-notes/release-notes-0.3.23.md
  doc/bitcoin-release-notes/release-notes-0.3.24.md
  doc/bitcoin-release-notes/release-notes-0.4.0.md
  doc/bitcoin-release-notes/release-notes-0.4.1.md
  doc/bitcoin-release-notes/release-notes-0.4.2.md
  doc/bitcoin-release-notes/release-notes-0.4.3.md
  doc/bitcoin-release-notes/release-notes-0.4.4.md
  doc/bitcoin-release-notes/release-notes-0.4.5.md
  doc/bitcoin-release-notes/release-notes-0.4.6.md
  doc/bitcoin-release-notes/release-notes-0.5.0.md
  doc/bitcoin-release-notes/release-notes-0.5.1.md
  doc/bitcoin-release-notes/release-notes-0.5.2.md
  doc/bitcoin-release-notes/release-notes-0.5.3.md
  doc/bitcoin-release-notes/release-notes-0.5.4.md
  doc/bitcoin-release-notes/release-notes-0.5.5.md
  doc/bitcoin-release-notes/release-notes-0.6.0.md
  doc/bitcoin-release-notes/release-notes-0.6.1.md
  doc/bitcoin-release-notes/release-notes-0.6.2.md
  doc/bitcoin-release-notes/release-notes-0.6.3.md
  doc/bitcoin-release-notes/release-notes-0.7.0.md
  doc/bitcoin-release-notes/release-notes-0.7.1.md
  doc/bitcoin-release-notes/release-notes-0.7.2.md
  doc/bitcoin-release-notes/release-notes-0.8.0.md
  doc/bitcoin-release-notes/release-notes-0.8.1.md
  doc/bitcoin-release-notes/release-notes-0.8.2.md
  doc/bitcoin-release-notes/release-notes-0.8.3.md
  doc/bitcoin-release-notes/release-notes-0.8.4.md
  doc/bitcoin-release-notes/release-notes-0.8.5.md
  doc/bitcoin-release-notes/release-notes-0.8.6.md
  doc/bitcoin-release-notes/release-notes-0.9.0.md
  doc/bitcoin-release-notes/release-notes-0.9.1.md
  doc/bitcoin-release-notes/release-notes-0.9.2.1.md
  doc/bitcoin-release-notes/release-notes-0.9.2.md
  doc/bitcoin-release-notes/release-notes-0.9.3.md
  doc/bitcoin-release-notes/release-notes-0.9.4.md
  doc/bitcoin-release-notes/release-notes-0.9.5.md
Labels: C-cleanup

#4766 Update ZeroMQ
  depends/funcs.mk
  depends/packages.md
  depends/packages/bdb.mk
  depends/packages/libevent.mk
  depends/packages/zeromq.mk
  doc/zmq.md
  qa/zcash/postponed-updates.txt
  src/zmq/zmqnotificationinterface.cpp
Labels: A-dependencies, C-upstream-port

#4772 Add logging when we receive an invalid note plaintext (using the "receiveunsafe" log category)
  src/init.cpp
  src/zcash/Note.cpp
Labels: A-logging, A-wallet

#4773 FFI: Merge librustzcash_init_zksnark_params variants into one function
  src/rust/src/rustzcash.rs
Labels: A-rust-ffi, C-cleanup

#4776 MOVEONLY: Move logging code from util.{h,cpp} to new files
  src/Makefile.am
  src/logging.cpp
  src/logging.h
  src/util.cpp
  src/util.h
Labels: A-logging, C-cleanup

#4777 Fix a new warning about use of boost::bind placeholders after updating Boost
  src/init.cpp
  src/rpc/server.cpp
  src/torcontrol.cpp
Labels: C-cleanup

#4779 depends: Use patch rather than sed in bdb package
  depends/packages/bdb.mk
  depends/patches/bdb/winioctl-and-atomic_init_db.patch
Labels: A-build, S-scratching-an-itch

#4775 depends: Postpone current and scheduled Rust releases until 2021
  qa/zcash/postponed-updates.txt
Labels: A-dependencies, S-committed

#4770 Add -ibdskiptxverification flag to allow faster synchronization.
  src/checkpoints.cpp
  src/checkpoints.h
  src/gtest/test_checkblock.cpp
  src/init.cpp
  src/main.cpp
  src/main.h
  src/test/checkblock_tests.cpp
Labels: A-consensus, I-performance, S-committed

#4570 Add timestamp to warnings
  src/init.cpp
  src/main.cpp
  src/main.h
  src/rpc/mining.cpp
  src/rpc/misc.cpp
  src/rpc/net.cpp
  src/test/alert_tests.cpp
  src/timedata.cpp
  src/warnings.cpp
  src/warnings.h
Labels: A-logging

#4784 performance: auto params = CChainParams::GetConsensus()
  src/gtest/test_foundersreward.cpp
  src/gtest/test_noteencryption.cpp
  src/gtest/test_transaction_builder.cpp
  src/gtest/test_validation.cpp
  src/main.cpp
  src/metrics.cpp
  src/rpc/mining.cpp
  src/wallet/asyncrpcoperation_saplingmigration.cpp
  src/wallet/test/rpc_wallet_tests.cpp
  src/zcbenchmarks.cpp
Labels: I-performance

#4782 simplify `TestBlockValidity()`
  src/main.cpp
  src/main.h
  src/miner.cpp
  src/rpc/mining.cpp
Labels: A-pow, C-cleanup

#4791 test: Fix various pyflakes warnings
  qa/rpc-tests/test_framework/equihash.py
  qa/rpc-tests/test_framework/mininode.py
Labels: A-testing, C-cleanup

#4789 Test suite portability fixes for macOS
  qa/zcash/full_test_suite.py
Labels: A-testing, O-macos, portability

#4787 Added libtinfo5 to ci builder containers
  contrib/ci-builders/Dockerfile-bbworker.apt
  contrib/ci-builders/Dockerfile-bbworker.arch
  contrib/ci-builders/Dockerfile-bbworker.centos8
  contrib/ci-builders/Dockerfile-build-python.apt
  contrib/ci-builders/Dockerfile-build.arch
  contrib/ci-builders/Dockerfile-build.centos8
  contrib/ci-builders/Dockerfile-gitian.apt
  contrib/ci-builders/apt-package-list.txt
  contrib/ci-builders/docker-build.sh
Labels: A-CI

#4797 log(x)/log(2.0) can be written as log2(x)
  src/main.cpp
Labels: C-cleanup

#4799 Fix integer types in DisplayDuration
  src/metrics.cpp
Labels: O-macos

#4800 Comment and error message cleanups for transaction checks
  src/main.cpp
Labels: I-error-handling, user interface

#4790 Add funding stream addresses to getblocksubsidy RPC output
  src/rpc/blockchain.cpp
  src/rpc/mining.cpp
  src/wallet/test/rpc_wallet_tests.cpp
Labels: A-pow, A-rpc-interface

#4794 allow getaddressutxos if -lightwalletd
  qa/rpc-tests/addressindex.py
  src/rpc/misc.cpp
Labels: A-explorer, A-light-clients, A-rpc-interface

#4613 Pin Clang for all compilation
  contrib/devtools/symbol-check.py
  depends/config.site.in
  depends/funcs.mk
  depends/hosts/default.mk
  depends/hosts/freebsd.mk
  depends/hosts/linux.mk
  depends/hosts/mingw32.mk
  depends/packages/bdb.mk
  depends/packages/boost.mk
  depends/packages/googletest.mk
  depends/packages/libcxx.mk
  depends/packages/native_cctools.mk
  depends/packages/native_clang.mk
  depends/packages/packages.mk
  depends/packages/zeromq.mk
  depends/patches/boost/iostreams-106.patch
  depends/patches/native_cctools/ignore-otool.diff
  depends/patches/zeromq/windows-unused-variables.diff
  doc/release-notes.md
  qa/zcash/full_test_suite.py
  qa/zcash/postponed-updates.txt
  qa/zcash/updatecheck.py
  src/Makefile.bench.include
  src/secp256k1/configure.ac
  src/univalue/Makefile.am
  src/wallet/gtest/test_wallet_zkeys.cpp
  src/wallet/test/rpc_wallet_tests.cpp
  zcutil/build.sh
Labels: A-build, A-dependencies, F-clang, S-committed

#4611 Require and build with C++17
  build-aux/m4/ax_cxx_compile_stdcxx.m4
  configure.ac
  contrib/debian/copyright
  depends/packages/bdb.mk
  depends/packages/boost.mk
  depends/packages/googletest.mk
  depends/packages/zeromq.mk
  src/leveldb/build_detect_platform
  src/random.h
  src/wallet/wallet.cpp
Labels: A-build, S-committed

#4803 Postpone native_ccache 4.0
  qa/zcash/postponed-updates.txt
Labels: A-dependencies

#4733 depends download: fix a logging bug for multi-archive packages:
  depends/Makefile
Labels: A-build

#4804 Update secp256k1 again
  configure.ac
  src/secp256k1/.travis.yml
  src/secp256k1/README.md
  src/secp256k1/configure.ac
  src/secp256k1/contrib/travis.sh
  src/secp256k1/sage/gen_exhaustive_groups.sage
  src/secp256k1/src/assumptions.h
  src/secp256k1/src/basic-config.h
  src/secp256k1/src/bench_internal.c
  src/secp256k1/src/ecmult.h
  src/secp256k1/src/ecmult_const_impl.h
  src/secp256k1/src/ecmult_impl.h
  src/secp256k1/src/group.h
  src/secp256k1/src/group_impl.h
  src/secp256k1/src/modules/ecdh/tests_impl.h
  src/secp256k1/src/modules/extrakeys/Makefile.am.include
  src/secp256k1/src/modules/extrakeys/main_impl.h
  src/secp256k1/src/modules/extrakeys/tests_exhaustive_impl.h
  src/secp256k1/src/modules/extrakeys/tests_impl.h
  src/secp256k1/src/modules/recovery/Makefile.am.include
  src/secp256k1/src/modules/recovery/tests_exhaustive_impl.h
  src/secp256k1/src/modules/recovery/tests_impl.h
  src/secp256k1/src/modules/schnorrsig/Makefile.am.include
  src/secp256k1/src/modules/schnorrsig/main_impl.h
  src/secp256k1/src/modules/schnorrsig/tests_exhaustive_impl.h
  src/secp256k1/src/modules/schnorrsig/tests_impl.h
  src/secp256k1/src/scalar.h
  src/secp256k1/src/scalar_4x64_impl.h
  src/secp256k1/src/scalar_8x32_impl.h
  src/secp256k1/src/scalar_impl.h
  src/secp256k1/src/scalar_low_impl.h
  src/secp256k1/src/scratch_impl.h
  src/secp256k1/src/secp256k1.c
  src/secp256k1/src/selftest.h
  src/secp256k1/src/testrand.h
  src/secp256k1/src/testrand_impl.h
  src/secp256k1/src/tests.c
  src/secp256k1/src/tests_exhaustive.c
  src/secp256k1/src/util.h
  src/secp256k1/src/valgrind_ctime_test.c
Labels: A-consensus, A-dependencies

#4805 Lightweight abstraction of boost::filesystem
  src/Makefile.am
  src/bench/bench_bitcoin.cpp
  src/bitcoin-cli.cpp
  src/bitcoind.cpp
  src/dbwrapper.cpp
  src/dbwrapper.h
  src/fs.cpp
  src/fs.h
  src/gtest/main.cpp
  src/gtest/test_deprecation.cpp
  src/gtest/test_foundersreward.cpp
  src/init.cpp
  src/logging.cpp
  src/logging.h
  src/main.cpp
  src/main.h
  src/net.cpp
  src/net.h
  src/rpc/protocol.cpp
  src/rpc/protocol.h
  src/rpc/server.cpp
  src/test/alert_tests.cpp
  src/test/checkblock_tests.cpp
  src/test/dbwrapper_tests.cpp
  src/test/streams_tests.cpp
  src/test/test_bitcoin.cpp
  src/test/test_bitcoin.h
  src/torcontrol.cpp
  src/util.cpp
  src/util.h
  src/wallet/db.cpp
  src/wallet/db.h
  src/wallet/gtest/test_paymentdisclosure.cpp
  src/wallet/gtest/test_wallet.cpp
  src/wallet/gtest/test_wallet_zkeys.cpp
  src/wallet/paymentdisclosuredb.cpp
  src/wallet/paymentdisclosuredb.h
  src/wallet/rpcdump.cpp
  src/wallet/rpcwallet.cpp
  src/wallet/test/rpc_wallet_tests.cpp
  src/wallet/wallet.cpp
  src/wallet/walletdb.cpp
  src/zcbenchmarks.cpp
Labels: C-cleanup, C-upstream-port

#4827 Verifier for scriptable changes
  autogen.sh
  contrib/devtools/gen-manpages.sh
  contrib/qos/tc.sh
  doc/developer-notes.md
  share/genbuild.sh
  test/lint/README.md
  test/lint/commit-script-check.sh
  test/lint/git-subtree-check.sh
Labels: C-upstream-port, S-committed, dev infrastructure

#4812 Improve reject reasons for unmet shielded requirements
  src/coins.cpp
  src/coins.h
  src/main.cpp
  src/test/coins_tests.cpp
Labels: A-consensus, A-rpc-interface, I-error-handling, S-committed, usability

#4744 add z_gettreestate RPC
  qa/rpc-tests/finalsaplingroot.py
  src/gtest/test_rpc.cpp
  src/rpc/blockchain.cpp
  src/rpc/server.h
Labels: A-light-clients, A-rpc-interface, S-committed

#4826 Replace BOOST_STATIC_ASSERT with static_assert
  src/chainparams.cpp
  src/crypto/equihash.cpp
  src/crypto/equihash.h
  src/main.cpp
  src/policy/policy.h
  src/zcash/IncrementalMerkleTree.hpp
  src/zcash/NoteEncryption.cpp
Labels: C-cleanup, C-upstream-port, S-committed

#4831 Shell script cleanups
  contrib/devtools/gen-manpages.sh
  contrib/tidy_datadir.sh
  share/genbuild.sh
Labels: C-bug, C-upstream-port

#4837 Fixes for Gitian builds
  contrib/gitian-descriptors/gitian-linux.yml
Labels: A-build, C-bug
