Repository zcash/zcash, pull requests merged in 2020-02, with the labels that each got.

#4258 Changing gtest to CamelCase
  src/gtest/test_block.cpp
  src/gtest/test_checktransaction.cpp
  src/gtest/test_equihash.cpp
  src/gtest/test_foundersreward.cpp
  src/gtest/test_joinsplit.cpp
  src/gtest/test_keystore.cpp
  src/gtest/test_libzcash_utils.cpp
  src/gtest/test_noteencryption.cpp
  src/gtest/test_rpc.cpp
  src/gtest/test_tautology.cpp
  src/gtest/test_txid.cpp
  src/wallet/gtest/test_wallet_zkeys.cpp
Labels: cleanup, scratching an itch, testing

#4334 Fix Boost compilation on macOS
  depends/packages/boost.mk
  depends/patches/boost/darwin.diff
Labels: bug, build, dependencies, macOS, scratching an itch

#4302 Add z_getnewaddress test
  src/wallet/test/rpc_wallet_tests.cpp
Labels: RPC interface, scratching an itch, testing

#4335 Remove libsnark preprocessor flags
  src/Makefile.am
  src/Makefile.gtest.include
Labels: build, cleanup, scratching an itch

#4348 Fix typo
  src/bench/bench.h
Labels: cleanup, documentation, testing

#4328 Reduce duplication in key_io decode
  src/key_io.cpp
Labels: cleanup

#4353 Add missing cases for Blossom in ContextualCheckBlock tests
  src/gtest/test_checkblock.cpp
Labels: scratching an itch, testing

#4360 Add destination wrapper functions
  src/chainparams.cpp
  src/rpc/misc.cpp
  src/script/standard.cpp
  src/script/standard.h
  src/wallet/test/rpc_wallet_tests.cpp
Labels: cleanup, scratching an itch

#4146 z_viewtransaction
  contrib/debian/copyright
  depends/packages/packages.mk
  depends/packages/utfcpp.mk
  qa/rpc-tests/wallet_listreceived.py
  src/wallet/rpcwallet.cpp
  src/wallet/wallet.cpp
  src/wallet/wallet.h
Labels: RPC interface, wallet

#4355 End diff with LF character
  depends/patches/boost/darwin.diff
Labels: cleanup, scratching an itch

#4356 remove debug noise from gtests
  src/gtest/test_mempoollimit.cpp
  src/wallet/gtest/test_paymentdisclosure.cpp
Labels: cleanup, scratching an itch, testing

#4362 Refactor shielded address logic
  src/Makefile.am
  src/gtest/test_keys.cpp
  src/gtest/test_keystore.cpp
  src/gtest/test_zip32.cpp
  src/key_io.h
  src/keystore.cpp
  src/keystore.h
  src/rpc/misc.cpp
  src/utiltest.h
  src/wallet/asyncrpcoperation_saplingmigration.cpp
  src/wallet/asyncrpcoperation_saplingmigration.h
  src/wallet/crypter.cpp
  src/wallet/crypter.h
  src/wallet/gtest/test_wallet.cpp
  src/wallet/gtest/test_wallet_zkeys.cpp
  src/wallet/rpcwallet.cpp
  src/wallet/wallet.cpp
  src/wallet/wallet.h
  src/wallet/walletdb.h
  src/zcash/Address.cpp
  src/zcash/Address.hpp
  src/zcash/address/sapling.cpp
  src/zcash/address/sapling.hpp
  src/zcash/address/sprout.cpp
  src/zcash/address/sprout.hpp
  src/zcash/address/zip32.cpp
  src/zcash/address/zip32.h
  src/zcbenchmarks.cpp
Labels: cleanup, wallet

#4366 Add release notes for z_viewtransaction
  doc/release-notes.md
Labels: documentation, release

#4369 Upstream PRs relating to strMiscWarning
  src/Makefile.am
  src/alert.h
  src/init.cpp
  src/main.cpp
  src/main.h
  src/test/alert_tests.cpp
  src/timedata.cpp
  src/util.cpp
  src/util.h
  src/warnings.cpp
  src/warnings.h
Labels: Bitcoin Core codebase

#3481 zcutil/fetch-params.sh unneeded --testnet arg should warn user
  zcutil/fetch-params.sh
Labels: PR_cleanup, spring_cleaning

#4379 Initialize ThreadNotifyWallets before additional blocks are imported
  src/init.cpp
  src/validationinterface.cpp
  src/validationinterface.h
Labels: Off To The Races, bug
