Repository zcash/zcash, pull requests merged in 2020-08, with the labels that each got.

#4646 Add new dependencies to updatecheck.py; extend the postponement deadline by a month
  qa/zcash/postponed-updates.txt
  qa/zcash/updatecheck.py
Labels: SECURITY, dependencies

#4567 Build BDB utilities
  .gitignore
  Makefile.am
  depends/packages/bdb.mk
  zcutil/distclean.sh
Labels: build

#4593 Refactor ProofVerifier
  src/Makefile.am
  src/bench/bench_bitcoin.cpp
  src/fuzzing/CheckBlock/fuzz.cpp
  src/gtest/main.cpp
  src/gtest/test_checkblock.cpp
  src/gtest/test_checktransaction.cpp
  src/gtest/test_dynamicusage.cpp
  src/gtest/test_joinsplit.cpp
  src/gtest/test_transaction.cpp
  src/gtest/test_transaction_builder.cpp
  src/gtest/test_validation.cpp
  src/init.cpp
  src/init.h
  src/main.cpp
  src/main.h
  src/primitives/transaction.cpp
  src/primitives/transaction.h
  src/proof_verifier.cpp
  src/proof_verifier.h
  src/test/checkblock_tests.cpp
  src/test/test_bitcoin.cpp
  src/test/transaction_tests.cpp
  src/transaction_builder.cpp
  src/transaction_builder.h
  src/utiltest.cpp
  src/utiltest.h
  src/wallet/asyncrpcoperation_mergetoaddress.cpp
  src/wallet/asyncrpcoperation_saplingmigration.cpp
  src/wallet/asyncrpcoperation_sendmany.cpp
  src/wallet/asyncrpcoperation_shieldcoinbase.cpp
  src/wallet/gtest/test_wallet.cpp
  src/wallet/rpcwallet.cpp
  src/wallet/walletdb.cpp
  src/zcash/JoinSplit.cpp
  src/zcash/JoinSplit.hpp
  src/zcash/Proof.cpp
  src/zcash/Proof.hpp
  src/zcbenchmarks.cpp
Labels: cleanup, performance, scratching an itch

#4653 depends: Revert to using upstreams as primary download paths
  depends/Makefile
  depends/README.md
  depends/funcs.mk
  qa/zcash/full_test_suite.py
Labels: dependencies, dev infrastructure, scratching an itch

#4642 Modernise macOS cross-compilation toolchain
  contrib/gitian-descriptors/gitian-osx.yml
  contrib/macdeploy/README.md
  contrib/macdeploy/gen-sdk
  depends/Makefile
  depends/README.md
  depends/builders/darwin.mk
  depends/funcs.mk
  depends/hosts/darwin.mk
  depends/packages/native_cctools.mk
  doc/release-notes.md
  src/util.cpp
Labels: Bitcoin Core codebase, build, macOS

#4460 Remove deprecated contrib utilities
  contrib/README.md
  contrib/init/README.md
  contrib/init/bitcoind.conf
  contrib/init/bitcoind.init
  contrib/init/bitcoind.openrc
  contrib/init/bitcoind.openrcconf
  contrib/init/bitcoind.service
  contrib/macdeploy/Base.lproj/InfoPlist.strings
  contrib/macdeploy/DS_Store
  contrib/macdeploy/LICENSE
  contrib/macdeploy/background.png
  contrib/macdeploy/background.psd
  contrib/macdeploy/background.tiff
  contrib/macdeploy/background@2x.png
  contrib/macdeploy/detached-sig-apply.sh
  contrib/macdeploy/detached-sig-create.sh
  contrib/macdeploy/fancy.plist
  contrib/seeds/README.md
  contrib/seeds/nodes_main.txt
  contrib/seeds/nodes_test.txt
  contrib/spendfrom/README.md
  contrib/spendfrom/setup.py
  contrib/spendfrom/spendfrom.py
  contrib/test-patches/README.md
  contrib/test-patches/temp-revert-2.patch
  contrib/verify-commits/gpg.sh
  contrib/verify-commits/pre-push-hook.sh
  contrib/verify-commits/trusted-git-root
  contrib/verify-commits/trusted-keys
  contrib/verify-commits/verify-commits.sh
  contrib/verifysfbinaries/README.md
  contrib/verifysfbinaries/verify.sh
Labels: simplification

#3952 Remove unnecessary patch in bdb.mk
  depends/packages/bdb.mk
Labels: build, dependencies, usi

#4656 depends: Fixes to build system
  depends/Makefile
  depends/funcs.mk
  depends/packages/native_rust.mk
  depends/packages/packages.mk
  qa/zcash/updatecheck.py
  src/rust/src/tracing_ffi.rs
Labels: build, dependencies, portability

#1665 Allow to configure the zk-SNARK parameters directory using `-paramsdir=`
  src/init.cpp
  src/util.cpp
Labels: usability, zkSNARK Parameter Deployment

#3593 Give a better error message for transaction expiry
  src/main.cpp
Labels: PR_cleanup, spring_cleaning

#4670 Update checksec.sh to slimm609/checksec.sh version 2.3.0
  contrib/debian/copyright
  qa/zcash/checksec.sh
  qa/zcash/full_test_suite.py
Labels: SECURITY, scratching an itch

#4659 Improvements to tracing initialization
  src/bitcoind.cpp
  src/init.cpp
  src/rust/src/tracing_ffi.rs
Labels: logging

#4657 Add support for logging fields in spans and events
  contrib/debian/copyright
  src/main.cpp
  src/net.cpp
  src/rust/include/tracing.h
  src/rust/include/tracing/map.h
  src/rust/src/tracing_ffi.rs
  src/util.cpp
  src/util.h
Labels: logging

#4619 Cleanups needed for Bazel but that have value on their own (updated)
  src/Makefile.gtest.include
  src/Makefile.test.include
  src/crypto/common.h
  src/gtest/test_block.cpp
  src/gtest/test_random.cpp
  src/gtest/test_transaction.cpp
  src/gtest/utils.cpp
  src/gtest/utils.h
  src/primitives/block.h
  src/test/alert_tests.cpp
  src/test/base58_tests.cpp
  src/test/rpc_tests.cpp
  src/test/script_tests.cpp
  src/test/sighash_tests.cpp
  src/test/test_util.cpp
  src/test/test_util.h
  src/test/transaction_tests.cpp
  src/wallet/test/rpc_wallet_tests.cpp
Labels: A-build, C-cleanup

#4674 ZIP 212 NCC fixes
  src/main.cpp
  src/wallet/rpcwallet.cpp
  src/zcash/Note.cpp
  src/zcash/prf.cpp
  src/zcash/prf.h
Labels: C-audit

#4654 Replace most libsodium usage with Rust crates
  src/bench/verification.cpp
  src/gtest/test_checktransaction.cpp
  src/gtest/test_joinsplit.cpp
  src/gtest/test_transaction.cpp
  src/main.cpp
  src/primitives/transaction.cpp
  src/primitives/transaction.h
  src/proof_verifier.cpp
  src/proof_verifier.h
  src/random.cpp
  src/random.h
  src/rpc/rawtransaction.cpp
  src/rust/include/librustzcash.h
  src/rust/include/rust/ed25519.h
  src/rust/include/rust/ed25519/types.h
  src/rust/src/ed25519.rs
  src/rust/src/rustzcash.rs
  src/serialize.h
  src/test/sighash_tests.cpp
  src/test/transaction_tests.cpp
  src/transaction_builder.cpp
  src/utiltest.cpp
  src/wallet/asyncrpcoperation_mergetoaddress.cpp
  src/wallet/asyncrpcoperation_mergetoaddress.h
  src/wallet/asyncrpcoperation_sendmany.cpp
  src/wallet/asyncrpcoperation_sendmany.h
  src/wallet/asyncrpcoperation_shieldcoinbase.cpp
  src/wallet/asyncrpcoperation_shieldcoinbase.h
  src/wallet/gtest/test_paymentdisclosure.cpp
  src/wallet/gtest/test_wallet.cpp
  src/wallet/paymentdisclosure.cpp
  src/wallet/paymentdisclosure.h
  src/wallet/rpcdisclosure.cpp
  src/wallet/rpcwallet.cpp
  src/zcash/JoinSplit.cpp
  src/zcash/JoinSplit.hpp
  src/zcash/NoteEncryption.cpp
  src/zcbenchmarks.cpp
Labels: A-dependencies, C-cleanup, L-rust

#4542 Organize transaction version checks.
  src/gtest/test_checkblock.cpp
  src/gtest/test_checktransaction.cpp
  src/gtest/test_mempool.cpp
  src/main.cpp
Labels: A-consensus, C-cleanup, S-scratching-an-itch

#4313 Increase code readability, make DEPRECATION use Single Source of Truth for Blocks/Hour
  src/deprecation.h
Labels: C-cleanup

#4685 wallet: lock cs_main while accessing chainActive
  src/wallet/wallet.cpp
Labels: C-bug
