Repository zcash/zcash, pull requests merged in 2021-04, with the labels that each got.

#2939 removed bashisms from build scripts
  zcutil/build.sh
  zcutil/fetch-params.sh
Labels: portability

#4999 Bitcoin 0.13 locking PRs
  src/keystore.cpp
  src/main.cpp
  src/scheduler.cpp
  src/sync.cpp
  src/sync.h
Labels: C-upstream-port, I-race

#5044 Delete spare mainnet Founders' Reward addresses that will never be used
  src/chainparams.cpp
Labels: C-cleanup

#5009 Bitcoin 0.14 locking PRs
  src/httpserver.cpp
  src/main.cpp
  src/net.cpp
  src/net.h
  src/rpc/net.cpp
  src/sync.h
  src/util.cpp
  src/utiltime.cpp
  src/wallet/db.cpp
  src/wallet/db.h
  src/wallet/wallet.cpp
  src/wallet/walletdb.cpp
  src/wallet/walletdb.h
Labels: C-upstream-port, I-race

#5012 Bitcoin 0.15 locking PRs
  src/Makefile.test.include
  src/checkqueue.h
  src/test/checkqueue_tests.cpp
Labels: C-upstream-port, I-race

#4988 Add feature flagging infrastructure to consensus parameters.
  src/Makefile.gtest.include
  src/chainparams.cpp
  src/consensus/params.cpp
  src/consensus/params.h
  src/consensus/upgrades.cpp
  src/gtest/test_feature_flagging.cpp
  src/main.cpp
  src/primitives/transaction.cpp
  src/primitives/transaction.h
Labels: network upgrade management

#5047 Bump dependency postponements
  qa/zcash/postponed-updates.txt
  qa/zcash/updatecheck.py
Labels: A-dependencies, release

#5055 Release v4.4.0-rc1
  README.md
  configure.ac
  contrib/debian/changelog
  contrib/gitian-descriptors/gitian-linux.yml
  doc/man/zcash-cli.1
  doc/man/zcash-tx.1
  doc/man/zcashd.1
  doc/release-notes/release-notes-4.4.0-rc1.md
  src/clientversion.h
  src/deprecation.h
Labels: release

#5058 Minor cleanups
  qa/pull-tester/rpc-tests.py
  qa/zcash/updatecheck.py
  src/addrdb.cpp
  src/addrdb.h
  src/miner.h
  src/net.cpp
  src/script/zcash_script.h
  src/test/bctest.py
  zcutil/clean.sh
Labels: C-cleanup

#5059 Postpone Clang 12
  qa/zcash/postponed-updates.txt
Labels: A-dependencies, release

#5060 book: Fix comment in metrics example, and clarify usage
  doc/book/src/user/metrics.md
Labels: A-documentation

#5061 Release v4.4.0
  README.md
  configure.ac
  contrib/debian/changelog
  contrib/gitian-descriptors/gitian-linux.yml
  doc/authors.md
  doc/man/zcash-cli.1
  doc/man/zcash-tx.1
  doc/man/zcashd.1
  doc/release-notes.md
  doc/release-notes/release-notes-4.4.0.md
  src/clientversion.h
  src/deprecation.h
Labels: release

#5026 Backport bloom filter improvements
  src/bench/rollingbloom.cpp
  src/bloom.cpp
  src/bloom.h
  src/chain.cpp
  src/core_read.cpp
  src/core_write.cpp
  src/init.cpp
  src/key.cpp
  src/main.cpp
  src/merkleblock.cpp
  src/pubkey.cpp
  src/pubkey.h
  src/reverselock.h
  src/test/bloom_tests.cpp
  src/test/crypto_tests.cpp
  src/test/net_tests.cpp
  src/test/script_tests.cpp
  src/test/util_tests.cpp
  src/torcontrol.cpp
  src/txmempool.cpp
  src/wallet/wallet.cpp
Labels: C-upstream-port, I-dos, safe-to-build

#5017 Bitcoin 0.16 locking PRs
  src/addrman.h
  src/httpserver.cpp
  src/keystore.h
  src/main.cpp
  src/rest.cpp
  src/rpc/blockchain.cpp
  src/sync.cpp
  src/sync.h
  src/wallet/crypter.h
  src/wallet/rpcwallet.cpp
  src/wallet/wallet.cpp
Labels: C-upstream-port, I-race, safe-to-build

#5064 Prevent mutex lock fail even if --enable-debug
  src/sync.cpp
Labels: C-upstream-port

#5078 Add Debian 11 CI-Builder
  contrib/ci-builders/docker-build.sh
Labels: safe-to-build
