Repository zcash/zcash, pull requests merged in 2021-12, with the labels that each got.

#5396 Prerequisites for adding unified addresses to the wallet.
  src/Makefile.am
  src/gtest/test_keys.cpp
  src/key_io.cpp
  src/keystore.h
  src/pubkey.h
  src/script/script.h
  src/script/standard.h
  src/wallet/gtest/test_orchard_zkeys.cpp
  src/wallet/wallet.h
  src/zcash/Address.cpp
  src/zcash/Address.hpp
  src/zcash/address/bip44.cpp
  src/zcash/address/bip44.h
  src/zcash/address/mnemonic.cpp
  src/zcash/address/mnemonic.h
  src/zcash/address/unified.cpp
  src/zcash/address/unified.h
  src/zcash/address/zip32.cpp
  src/zcash/address/zip32.h
Labels: safe-to-build

#5421 Check the output of zip339_phrase_to_seed in MnemonicSeed initialization.
  src/gtest/test_keystore.cpp
  src/utiltest.cpp
  src/zcash/address/mnemonic.cpp
  src/zcash/address/mnemonic.h
Labels: safe-to-build

#5423 Batch-verify Orchard transactions at the block level.
  src/main.cpp
Labels: C-bug

#5422 Dont log ERROR: spent index not enabled
  doc/release-notes.md
  src/main.cpp
Labels: C-bug, A-rpc-interface, A-logging, I-dos, A-light-clients, safe-to-build

#5424 Update dependencies for 4.6.0
  contrib/devtools/update-rust-hashes.sh
  depends/packages/boost.mk
  depends/packages/native_rust.mk
  qa/zcash/postponed-updates.txt
Labels: A-dependencies

#5403 test: automatically add missing nuparams (network upgrade heights)
  qa/pull-tester/rpc-tests.py
  qa/rpc-tests/nuparams.py
  src/init.cpp
Labels: A-testing, use case, usability

#5427 rust: Remove misleading log message
  src/rust/src/address_ffi.rs
Labels: C-bug, A-logging

#5398 `ed25519-zebra` 3
  Cargo.lock
  Cargo.toml
Labels: A-dependencies, L-rust, S-committed, safe-to-build

#5404 [rpc] mining: Omit uninitialized currentblockweight, currentblocktx
  doc/release-notes.md
  qa/pull-tester/rpc-tests.py
  qa/rpc-tests/getmininginfo.py
  src/main.h
  src/miner.cpp
  src/rpc/mining.cpp
Labels: C-bug, C-upstream-port, A-rpc-interface, S-committed

#5402 Add defaultroots field to getblocktemplate
  qa/rpc-tests/getblocktemplate.py
  src/rpc/mining.cpp
Labels: C-bug, A-pow, S-committed, safe-to-build

#5426 Revert lint: Fix false positive
  zcutil/fetch-params.sh
Labels: I-regression, O-macos, safe-to-build

#5429 Pre-4.6.0-rc1 changes
  Cargo.lock
  Cargo.toml
  doc/release-notes.md
  src/rust/src/address_ffi.rs
  src/rust/src/rustzcash.rs
Labels: A-dependencies, L-rust, A-rust-ffi

#5430 Release v4.6.0-rc1
  README.md
  configure.ac
  contrib/debian/changelog
  contrib/gitian-descriptors/gitian-linux.yml
  doc/man/zcash-cli.1
  doc/man/zcash-tx.1
  doc/man/zcashd.1
  doc/release-notes/release-notes-4.6.0-rc1.md
  src/clientversion.h
  src/deprecation.h
Labels: release

#5300 Feature/wallet orchard UA RPCs
  src/experimental_features.cpp
  src/experimental_features.h
  src/init.cpp
  src/rpc/client.cpp
  src/test/util_tests.cpp
  src/utilstrencodings.cpp
  src/utilstrencodings.h
  src/wallet/rpcwallet.cpp
  src/wallet/test/rpc_wallet_tests.cpp
Labels: S-committed, safe-to-build

#5434 update librustzcash hash in config.offline, and remove all other repos from config.offline
  .cargo/config.offline
Labels: A-build, L-rust

#5431 test: Use result of getblocktemplate to submitblock
  qa/rpc-tests/getblocktemplate.py
  qa/rpc-tests/test_framework/mininode.py
  qa/rpc-tests/test_framework/zip244.py
  src/rpc/mining.cpp
Labels: A-testing, A-pow, S-committed

#5441 test: assert that the return value of submitblock is None
  qa/rpc-tests/getblocktemplate.py
Labels: A-testing, A-pow, A-rpc-interface, L-python

#5443 Lock cs_main prior to calling blockToJSON
  src/gtest/test_rpc.cpp
Labels: A-testing
