Repository zcash/zcash, pull requests merged in 2021-11, with the labels that each got.

#5367 Update entrypoint.sh
  contrib/docker/entrypoint.sh
Labels: safe-to-build

#5355 Update support for FreeBSD
  depends/builders/freebsd.mk
  depends/packages/native_clang.mk
Labels: A-build, A-dependencies, O-freebsd, safe-to-build

#5388 CI: Add Pyflakes to lints workflow
  .github/workflows/lints.yml
Labels: A-CI, L-python

#5374 Fix typos
  .github/ISSUE_TEMPLATE/bug-report.md
  doc/book/src/dev/rust.md
  doc/release-process.md
  qa/rpc-tests/finalsaplingroot.py
  qa/rpc-tests/fundrawtransaction.py
  qa/rpc-tests/merkle_blocks.py
  qa/rpc-tests/nodehandling.py
  qa/rpc-tests/p2p-fullblocktest.py
  qa/rpc-tests/pruning.py
  qa/rpc-tests/smartfees.py
  qa/rpc-tests/upgrade_golden.py
  qa/rpc-tests/wallet_import_export.py
  qa/rpc-tests/wallet_persistence.py
  qa/rpc-tests/zapwallettxes.py
  qa/zcash/checksec.sh
  src/bench/perf.cpp
  src/init.cpp
  src/main.cpp
  src/mempool_limit.cpp
  src/miner.cpp
  src/net.h
  src/policy/fees.h
  src/pow/tromp/equi_miner.h
  src/rust/include/rust/VA_OPT.hpp
  src/support/cleanse.cpp
  src/test/addrman_tests.cpp
  src/test/bitcoin-util-test.py
  src/test/checkqueue_tests.cpp
  src/test/data/script_valid.json
  src/test/data/tx_invalid.json
  src/test/data/tx_valid.json
  src/test/limitedmap_tests.cpp
  src/test/miner_tests.cpp
  src/torcontrol.cpp
  src/wallet/gtest/test_wallet.cpp
  src/wallet/rpcwallet.cpp
  src/wallet/test/rpc_wallet_tests.cpp
Labels: safe-to-build

#5306 Derive random HD seeds from ZIP-339 seed phrases.
  Cargo.lock
  Cargo.toml
  doc/release-notes.md
  qa/rpc-tests/wallet_broadcast.py
  qa/rpc-tests/wallet_import_export.py
  src/bench/verification.cpp
  src/chainparams.cpp
  src/chainparams.h
  src/gtest/test_keys.cpp
  src/gtest/test_keystore.cpp
  src/gtest/test_zip32.cpp
  src/init.cpp
  src/key.cpp
  src/key.h
  src/key_constants.h
  src/keystore.cpp
  src/keystore.h
  src/rpc/protocol.h
  src/rust/include/librustzcash.h
  src/rust/src/rustzcash.rs
  src/rust/src/zip339_ffi.rs
  src/sendalert.cpp
  src/serialize.h
  src/test/DoS_tests.cpp
  src/test/alert_tests.cpp
  src/test/bip32_tests.cpp
  src/test/key_tests.cpp
  src/test/multisig_tests.cpp
  src/test/sanity_tests.cpp
  src/test/script_P2SH_tests.cpp
  src/test/script_standard_tests.cpp
  src/test/script_tests.cpp
  src/test/sigopcount_tests.cpp
  src/test/test_bitcoin.cpp
  src/test/transaction_tests.cpp
  src/uint256.h
  src/utiltest.cpp
  src/wallet/asyncrpcoperation_saplingmigration.cpp
  src/wallet/asyncrpcoperation_sendmany.cpp
  src/wallet/crypter.cpp
  src/wallet/crypter.h
  src/wallet/gtest/test_wallet.cpp
  src/wallet/gtest/test_wallet_zkeys.cpp
  src/wallet/rpcdump.cpp
  src/wallet/rpcwallet.cpp
  src/wallet/test/rpc_wallet_tests.cpp
  src/wallet/test/wallet_test_fixture.cpp
  src/wallet/wallet.cpp
  src/wallet/wallet.h
  src/wallet/walletdb.cpp
  src/wallet/walletdb.h
  src/zcash/Address.cpp
  src/zcash/address/zip32.cpp
  src/zcash/address/zip32.h
  src/zcbenchmarks.cpp
  test/lint/lint-includes.sh
Labels: A-wallet, A-crypto, S-committed, safe-to-build

#5373 Add legacy sigops counts to the zcash_script library API
  src/Makefile.am
  src/primitives/transaction.cpp
  src/primitives/tx_version_info.cpp
  src/rust/src/incremental_sinsemilla_tree_ffi.rs
  src/rust/src/orchard_ffi.rs
  src/rust/src/rustzcash.rs
  src/script/zcash_script.cpp
  src/script/zcash_script.h
Labels: safe-to-build, A-lib-script

#5356 Rename OrchardMerkleTree -> OrchardMerkleFrontier
  src/coins.cpp
  src/coins.h
  src/gtest/test_merkletree.cpp
  src/main.cpp
  src/primitives/orchard.h
  src/rust/include/rust/orchard/incremental_merkle_tree.h
  src/rust/include/rust/orchard/incremental_sinsemilla_tree.h
  src/rust/src/incremental_merkle_tree_ffi.rs
  src/rust/src/rustzcash.rs
  src/test/coins_tests.cpp
  src/txdb.cpp
  src/txdb.h
  src/zcash/IncrementalMerkleTree.hpp
  src/zcbenchmarks.cpp
Labels: S-committed, safe-to-build

#5389 correct typo
  contrib/docker/README.md
Labels: safe-to-build

#5357 Add Orchard Address, IncomingViewingKey, and FullViewingKey types.
  Cargo.lock
  Cargo.toml
  src/Makefile.am
  src/Makefile.gtest.include
  src/rust/include/rust/orchard/keys.h
  src/rust/src/orchard_keys_ffi.rs
  src/rust/src/rustzcash.rs
  src/wallet/gtest/test_orchard_zkeys.cpp
  src/wallet/wallet.cpp
  src/wallet/wallet.h
  src/zcash/Address.hpp
  src/zcash/address/orchard.cpp
  src/zcash/address/orchard.hpp
  src/zcash/address/zip32.cpp
  src/zcash/address/zip32.h
Labels: A-rust-ffi, S-committed, safe-to-build, A-orchard
