Repository zcash/zcash, pull requests merged in 2021-08, with the labels that each got.

#5268 Optimise reindex
  qa/rpc-tests/reindex.py
  src/init.cpp
  src/main.cpp
  src/main.h
  src/ui_interface.h
  src/wallet/gtest/test_wallet_zkeys.cpp
Labels: I-performance, C-upstream-port

#5265 ZIP 239 preparations 1
  qa/rpc-tests/p2p_txexpiringsoon.py
  qa/rpc-tests/shorter_block_times.py
  qa/rpc-tests/tx_expiry_helper.py
  src/main.cpp
  src/main.h
  src/net.cpp
  src/net.h
  src/test/DoS_tests.cpp
  src/txmempool.cpp
  src/txmempool.h
Labels: C-upstream-port

#5269 ZIP 239 preparations 2
  qa/rpc-tests/prioritisetransaction.py
  src/amount.h
  src/gtest/test_mempool.cpp
  src/main.cpp
  src/main.h
  src/net.cpp
  src/net.h
  src/rpc/blockchain.cpp
  src/test/mempool_tests.cpp
  src/test/test_bitcoin.cpp
  src/test/test_bitcoin.h
  src/txmempool.cpp
  src/txmempool.h
Labels: safe-to-build

#5278 Update URL for Boost source download (from dl.bintray.com to boostorg.jfrog.io)
  depends/packages/boost.mk
Labels: A-dependencies

#5274 ZIP 239 preparations 3
  src/main.cpp
  src/memusage.h
  src/net.cpp
  src/net.h
  src/protocol.cpp
  src/protocol.h
  src/test/policyestimator_tests.cpp
  src/txmempool.cpp
  src/txmempool.h
Labels: C-upstream-port, A-networking, A-mempool, safe-to-build, NU5

#5275 ZIP 239 preparations 4
  qa/pull-tester/rpc-tests.py
  qa/rpc-tests/bip65-cltv-p2p.py
  qa/rpc-tests/bipdersig-p2p.py
  qa/rpc-tests/fundrawtransaction.py
  qa/rpc-tests/getblocktemplate_proposals.py
  qa/rpc-tests/invalidblockrequest.py
  qa/rpc-tests/invalidtxrequest.py
  qa/rpc-tests/multi_rpc.py
  qa/rpc-tests/p2p-fullblocktest.py
  qa/rpc-tests/pruning.py
  qa/rpc-tests/rawtransactions.py
  qa/rpc-tests/rest.py
  qa/rpc-tests/test_framework/comptool.py
  qa/rpc-tests/test_framework/mininode.py
  qa/rpc-tests/test_framework/netutil.py
  qa/rpc-tests/test_framework/script.py
  qa/rpc-tests/wallet.py
  src/consensus/validation.h
  src/gtest/test_checkblock.cpp
  src/gtest/test_checktransaction.cpp
  src/gtest/test_validation.cpp
  src/init.cpp
  src/main.cpp
  src/main.h
Labels: C-upstream-port, A-rpc-interface, A-networking, A-logging, NU5

#5266 ZIP 339 support
  Cargo.lock
  Cargo.toml
  src/rust/include/rust/zip339.h
  src/rust/src/rustzcash.rs
  src/rust/src/tests/mod.rs
  src/rust/src/tests/zip339.rs
  src/rust/src/zip339_ffi.rs
  src/test/data/unified_addrs.json
Labels: safe-to-build

#5251 Use manual serialization for Merkle frontiers rather than bincode.
  Cargo.lock
  Cargo.toml
  src/rust/src/address_ffi.rs
  src/rust/src/history_ffi.rs
  src/rust/src/orchard_ffi/incremental_sinsemilla_tree_ffi.rs
  src/rust/src/rustzcash.rs
  src/rust/src/tests/key_agreement.rs
  src/rust/src/tests/signatures.rs
Labels: L-rust, A-rust-ffi, safe-to-build, NU5

#5279 Tweaks to CI lints
  .github/workflows/lints.yml
  src/net.h
  src/test/data/merkle_roots_orchard.h
Labels: A-CI, S-committed, safe-to-build

#5280 Lock the wallet in SetBestChainINTERNAL
  src/validationinterface.cpp
  src/wallet/wallet.h
Labels: S-committed, safe-to-build
