Repository zcash/zcash, pull requests merged in 2021-09, with the labels that each got.

#5286 CI: Add Dependabot config to keep Actions up-to-date
  .github/dependabot.yml
Labels: A-CI

#5283 Fix v5 transaction format
  qa/rpc-tests/mempool_nu_activation.py
  qa/rpc-tests/remove_sprout_shielding.py
  qa/rpc-tests/test_framework/mininode.py
  src/main.cpp
  src/main.h
  src/primitives/transaction.cpp
  src/primitives/transaction.h
  src/transaction_builder.cpp
  src/transaction_builder.h
  src/wallet/rpcwallet.cpp
Labels: C-bug, A-testing, S-committed, safe-to-build, NU5, A-parsing

#5284 Sort taddr txns by txindex in addition to height
  src/rpc/misc.cpp
Labels: A-rpc-interface, A-explorer, safe-to-build

#5295 Update authors of librustzcash to everyone currently and formerly on Core team (in alphabetical order)
  Cargo.toml
Labels: A-packaging

#5299 Update dependencies for 4.5.0
  Cargo.lock
  Cargo.toml
  depends/packages/boost.mk
  depends/packages/native_rust.mk
  depends/patches/boost/deprecated-two-arg-allocate.diff
  depends/patches/boost/iostreams-106.patch
  depends/patches/boost/signals2-noise.patch
  qa/zcash/postponed-updates.txt
  rust-toolchain
  src/rust/src/orchard_ffi.rs
Labels: A-dependencies

#5293 Smoke Test Updates (Remove Sprout Logic )
  qa/zcash/smoke_tests.py
Labels: A-testing, L-python, safe-to-build

#5291 ZIP 239 support
  doc/book/src/SUMMARY.md
  doc/book/src/design/p2p-data-propagation.md
  qa/pull-tester/rpc-tests.py
  qa/rpc-tests/feature_zip239.py
  qa/rpc-tests/test_framework/mininode.py
  qa/rpc-tests/test_framework/script.py
  qa/rpc-tests/test_framework/zip244.py
  qa/rpc-tests/tx_expiry_helper.py
  src/main.cpp
  src/net.cpp
  src/net.h
  src/primitives/transaction.cpp
  src/primitives/transaction.h
  src/protocol.cpp
  src/protocol.h
  src/rpc/rawtransaction.cpp
  src/uint256.h
  src/version.h
Labels: A-networking, NU5

#5303 ZIP 239: Reject unknown CInv message types
  qa/rpc-tests/feature_zip239.py
  qa/rpc-tests/test_framework/mininode.py
  src/main.cpp
  src/protocol.h
Labels: A-networking, D-bitcoin-divergence, NU5

#5304 Release v4.5.0-rc1
  Cargo.lock
  Cargo.toml
  README.md
  configure.ac
  contrib/debian/changelog
  contrib/gitian-descriptors/gitian-linux.yml
  doc/man/zcash-cli.1
  doc/man/zcash-tx.1
  doc/man/zcashd.1
  doc/release-notes/release-notes-4.5.0-rc1.md
  src/clientversion.h
  src/deprecation.h
  src/key_io.cpp
  src/rust/include/rust/address.h
  src/rust/src/address_ffi.rs
  src/rust/src/orchard_ffi/incremental_sinsemilla_tree_ffi.rs
  src/test/data/unified_addrs.json
  src/zcash/Address.cpp
  src/zcash/Address.hpp
Labels: release, A-dependencies, A-rust-ffi

#5307 Fix Gitian builds
  .cargo/config.offline
  src/Makefile.am
  src/Makefile.gtest.include
Labels: A-build

#5311 Fix regression in wallet load performance
  src/rust/src/orchard_ffi.rs
  src/wallet/walletdb.cpp
Labels: C-bug, I-performance, I-regression, L-rust, A-rust-ffi, A-wallet-database, A-orchard

#5305 contrib: Add script for generating a graph of our Rust dependencies
  Cargo.lock
  contrib/devtools/rust-deps-graph.sh
Labels: A-dependencies

#5320 Final dependecy updates for 4.5.0
  .cargo/config.offline
  Cargo.lock
  Cargo.toml
  contrib/debian/copyright
Labels: A-dependencies, licensing, safe-to-build

#5322 Release v4.5.0
  README.md
  configure.ac
  contrib/debian/changelog
  contrib/gitian-descriptors/gitian-linux.yml
  doc/authors.md
  doc/man/zcash-cli.1
  doc/man/zcash-tx.1
  doc/man/zcashd.1
  doc/release-notes/release-notes-4.5.0.md
  src/chainparams.cpp
  src/clientversion.h
  src/deprecation.h
  src/version.h
Labels: release, NU5

#5326 wallet: Check spent shielded notes in CWalletTx::IsFromMe
  doc/release-notes.md
  qa/pull-tester/rpc-tests.py
  qa/rpc-tests/wallet_isfromme.py
  src/wallet/wallet.cpp
  src/wallet/wallet.h
Labels: C-bug, A-wallet, A-rpc-interface

#5330 Fix bugs in testnet Orchard circuit
  .cargo/config.offline
  Cargo.lock
  Cargo.toml
  doc/release-notes.md
  qa/rpc-tests/feature_zip244_blockcommitments.py
  qa/rpc-tests/mempool_nu_activation.py
  qa/rpc-tests/test_framework/mininode.py
  qa/rpc-tests/test_framework/util.py
  src/chainparams.cpp
  src/consensus/upgrades.cpp
  src/test/data/zip0244.json
  src/version.h
Labels: C-bug, A-consensus, A-circuit, testnet, NU5

#5331 depends: Postpone native_ccache 4.4.2
  qa/zcash/postponed-updates.txt
Labels: A-dependencies

#5332 Release v4.5.1
  README.md
  configure.ac
  contrib/debian/changelog
  contrib/gitian-descriptors/gitian-linux.yml
  doc/authors.md
  doc/man/zcash-cli.1
  doc/man/zcash-tx.1
  doc/man/zcashd.1
  doc/release-notes.md
  doc/release-notes/release-notes-4.5.1.md
  src/clientversion.h
Labels: release

#5315 Add buster to the list of suites used by gitian
  contrib/gitian-descriptors/gitian-linux.yml
Labels: A-build, O-linux
