Repository zcash/zcash, pull requests merged in 2021-02, with the labels that each got.

#4979 Backport of bitcoin/bitcoin#8020
  src/coins.cpp
  src/coins.h
  src/hash.cpp
  src/hash.h
  src/main.cpp
  src/test/hash_tests.cpp
  src/transaction_builder.cpp
  src/txmempool.cpp
  src/txmempool.h
  src/uint256.cpp
  src/uint256.h
  src/wallet/asyncrpcoperation_mergetoaddress.cpp
  src/wallet/asyncrpcoperation_sendmany.cpp
Labels: C-upstream-port, I-dos

#4985 Use SipHash for node eviction
  src/coins.cpp
  src/coins.h
  src/hash.cpp
  src/hash.h
  src/main.cpp
  src/net.cpp
  src/net.h
  src/test/hash_tests.cpp
Labels: C-upstream-port

#2812 banlist.dat: store banlist on disk
  qa/rpc-tests/nodehandling.py
  src/Makefile.am
  src/Makefile.test.include
  src/addrdb.cpp
  src/addrdb.h
  src/main.cpp
  src/net.cpp
  src/net.h
  src/netbase.cpp
  src/netbase.h
  src/rpc/net.cpp
  src/test/net_tests.cpp
  src/test/netbase_tests.cpp
  src/test/rpc_tests.cpp
  src/ui_interface.h
Labels: A-networking, C-upstream-port

#4989 Whitespace-only fix in chainparams.cpp
  src/chainparams.cpp
Labels: C-cleanup

#4986 zcash_script: Add API to verify scripts with precomputed tx data
  src/script/zcash_script.cpp
  src/script/zcash_script.h
Labels: A-lib-script

#2816 Introduce -maxuploadtarget
  doc/reduce-traffic.md
  doc/release-notes.md
  qa/pull-tester/rpc-tests.py
  qa/rpc-tests/maxuploadtarget.py
  src/init.cpp
  src/main.cpp
  src/net.cpp
  src/net.h
  src/rpc/net.cpp
Labels: A-networking, C-upstream-port, I-performance, S-scratching-an-itch

#4972 Remove bad chain alert partition check
  src/init.cpp
  src/main.cpp
  src/main.h
  src/test/alert_tests.cpp
Labels: C-upstream-port

#4973 test: Convert Bech32 test vectors into known-answer test vectors
  src/test/bech32_tests.cpp
Labels: A-testing, upstreamable

#4991 FastRandomContext improvements and switch to ChaCha20
  configure.ac
  src/Makefile.am
  src/Makefile.test.include
  src/addrman.cpp
  src/addrman.h
  src/bench/checkqueue.cpp
  src/crypto/chacha20.cpp
  src/crypto/chacha20.h
  src/crypto/common.h
  src/net.h
  src/random.cpp
  src/random.h
  src/test/addrman_tests.cpp
  src/test/crypto_tests.cpp
  src/test/prevector_tests.cpp
  src/test/random_tests.cpp
  src/test/test_bitcoin.cpp
  src/test/test_random.h
Labels: C-upstream-port

#4993 Update/postpone dependencies for v4.3.0
  Cargo.lock
  qa/zcash/postponed-updates.txt
Labels: A-dependencies

#4994 Bitcoin 0.12 misc P2P/Net PRs
  src/Makefile.test.include
  src/init.cpp
  src/limitedmap.h
  src/main.cpp
  src/net.h
  src/test/limitedmap_tests.cpp
  src/timedata.cpp
Labels: A-networking, C-upstream-port

#4992 Bitcoin 0.12 locking PRs
  src/rpc/rawtransaction.cpp
  src/wallet/walletdb.cpp
Labels: C-upstream-port, I-race

#4995 Fill out release notes for v4.3.0
  doc/release-notes.md
Labels: release

#4998 Release v4.3.0-rc1
  README.md
  configure.ac
  contrib/debian/changelog
  contrib/gitian-descriptors/gitian-linux.yml
  doc/man/zcash-cli.1
  doc/man/zcash-tx.1
  doc/man/zcashd.1
  doc/release-notes/release-notes-4.3.0-rc1.md
  src/clientversion.h
  src/deprecation.h
Labels: release

#5000 Update Rust dependencies for 4.3.0
  Cargo.lock
  Cargo.toml
Labels: A-dependencies

#5002 add libxml2
  contrib/gitian-descriptors/gitian-linux.yml
Labels: A-build

#5001 add zstd package to support Windows cross compile
  contrib/ci-builders/apt-package-list.txt
Labels: A-build, O-windows

#5010 Release v4.3.0
  README.md
  configure.ac
  contrib/debian/changelog
  contrib/gitian-descriptors/gitian-linux.yml
  doc/authors.md
  doc/man/zcash-cli.1
  doc/man/zcash-tx.1
  doc/man/zcashd.1
  doc/release-notes.md
  doc/release-notes/release-notes-4.3.0.md
  src/clientversion.h
  src/deprecation.h
Labels: release

#5011 CI: Correctly build zcashd book
  .github/workflows/book.yml
Labels: A-documentation

#5007 Ignore temporary build artifacts.
  .gitignore
Labels: A-build
