Repository zcash/zcash, pull requests merged in 2021-03, with the labels that each got.

#5015 Fix build regression by adding #include <atomic>
  src/net.h
Labels: A-build

#4997 Replace setInventoryKnown with a rolling bloom filter
  src/Makefile.am
  src/Makefile.test.include
  src/main.cpp
  src/mruset.h
  src/net.cpp
  src/net.h
  src/test/mruset_tests.cpp
Labels: A-networking, C-upstream-port

#5036 Rust 1.51.0 and zcash_* 0.5.0
  Cargo.lock
  Cargo.toml
  depends/packages/native_rust.mk
  qa/zcash/postponed-updates.txt
  qa/zcash/updatecheck.py
  rust-toolchain
  src/rust/src/rustzcash.rs
  src/rust/src/tests/key_agreement.rs
  src/rust/src/tests/key_components.rs
  src/rust/src/tests/mod.rs
  src/rust/src/tests/notes.rs
  src/rust/src/tests/signatures.rs
Labels: A-dependencies, A-rust-ffi

#4947 Add metrics collection and a Prometheus exporter
  Cargo.lock
  Cargo.toml
  contrib/debian/copyright
  contrib/metrics/prometheus.yaml
  doc/book/src/SUMMARY.md
  doc/book/src/user.md
  doc/book/src/user/metrics.md
  doc/release-notes.md
  src/init.cpp
  src/main.cpp
  src/net.cpp
  src/net.h
  src/rust/include/rust/VA_OPT.hpp
  src/rust/include/rust/helpers.h
  src/rust/include/rust/map.h
  src/rust/include/rust/metrics.h
  src/rust/include/tracing.h
  src/rust/src/metrics_ffi.rs
  src/rust/src/metrics_ffi/prometheus.rs
  src/rust/src/rustzcash.rs
  src/util.cpp
Labels: A-metrics, A-rust-ffi

#4996 Add -blocksonly option
  doc/reduce-traffic.md
  src/init.cpp
  src/main.cpp
  src/main.h
  src/net.cpp
  src/net.h
  src/rpc/net.cpp
Labels: A-networking, C-upstream-port, I-performance

#5043 native_rust: don't install Rust docs
  depends/packages/native_rust.mk
Labels: A-dependencies, safe-to-build
