Repository zcash/zcash, pull requests merged in 2021-01, with the labels that each got.

#4913 Reduce the dependencies of libzcashconsensus
  src/compat/endian.h
  src/crypto/common.h
  src/gtest/main.cpp
  src/gtest/test_checktransaction.cpp
  src/gtest/test_joinsplit.cpp
  src/gtest/test_timedata.cpp
  src/gtest/test_transaction.cpp
  src/init.cpp
  src/logging.cpp
  src/mempool_limit.cpp
  src/mempool_limit.h
  src/miner.h
  src/prevector.h
  src/primitives/transaction.cpp
  src/primitives/transaction.h
  src/test/coins_tests.cpp
  src/test/test_bitcoin.cpp
  src/test/transaction_tests.cpp
  src/transaction_builder.cpp
  src/transaction_builder.h
  src/util.h
  src/utiltest.cpp
  src/wallet/asyncrpcoperation_mergetoaddress.cpp
  src/wallet/asyncrpcoperation_sendmany.cpp
  src/wallet/asyncrpcoperation_shieldcoinbase.cpp
  src/wallet/gtest/test_wallet.cpp
  src/wallet/rpcdisclosure.cpp
  src/wallet/rpcwallet.cpp
  src/wallet/wallet.cpp
  src/wallet/wallet.h
  src/zcash/Note.cpp
  src/zcbenchmarks.cpp
Labels: A-lib-script

#4924 qa/zcash/updatecheck.py: remove dead code; print instructions to run `cargo outdated` and `cargo update`
  qa/zcash/updatecheck.py
Labels: A-dependencies

#4942 depends: Update Rust to 1.49.0
  Cargo.lock
  depends/packages/native_rust.mk
  qa/zcash/postponed-updates.txt
  rust-toolchain
  src/rust/src/rustzcash.rs
Labels: A-dependencies

#4944 Skip "tx" messages during initial block download.
  src/main.cpp
Labels: A-networking, I-performance

#4937 Add support for FreeBSD 12
  configure.ac
  depends/config.site.in
  depends/packages/bdb.mk
  depends/packages/boost.mk
  depends/packages/googletest.mk
  depends/packages/libcxx.mk
  depends/packages/native_clang.mk
  depends/packages/native_rust.mk
  depends/packages/zeromq.mk
  depends/patches/zeromq/windows-unused-variables.diff
Labels: A-build, O-freebsd

#4935 #4624 improve IBD sync by eliminating getheaders requests
  src/main.cpp
Labels: A-chain-sync, I-performance

#4934 Split wallet.py
  qa/pull-tester/rpc-tests.py
  qa/rpc-tests/wallet.py
  qa/rpc-tests/wallet_broadcast.py
  qa/rpc-tests/wallet_parsing_amounts.py
  qa/rpc-tests/wallet_z_sendmany.py
  qa/rpc-tests/wallet_zero_value.py
Labels: A-testing, C-cleanup

#4950 Boost build backports
  Makefile.am
  depends/Makefile
  depends/hosts/default.mk
  depends/packages/boost.mk
  depends/packages/native_b2.mk
  depends/packages/packages.mk
Labels: C-upstream-port

#4951 depends: Move to Clang 11
  depends/packages/boost.mk
  depends/packages/libcxx.mk
  depends/packages/native_clang.mk
  depends/patches/boost/deprecated-two-arg-allocate.diff
Labels: A-build, A-dependencies

#4956 depends: Allow per-host package download paths
  depends/funcs.mk
  depends/packages/native_clang.mk
Labels: A-build, C-bug, O-macos

#4754 Ensure that `CONFIGURE_FLAGS=--enable-debug` correctly uses -O0 for dependencies and main build
  depends/hosts/darwin.mk
  depends/hosts/freebsd.mk
  depends/hosts/linux.mk
  depends/hosts/mingw32.mk
  zcutil/build.sh
Labels: A-build, S-committed

#4959 Dependency updates
  Cargo.lock
  depends/packages/boost.mk
  depends/packages/zeromq.mk
  depends/patches/boost/iostreams-106.patch
  depends/patches/boost/signals2-noise.patch
  qa/zcash/postponed-updates.txt
  qa/zcash/updatecheck.py
Labels: A-dependencies

#4961 Prepare for LevelDB 1.22 update
  configure.ac
Labels: A-build, C-upstream-port

#4968 Set up an mdbook in which we can document zcashd's architecture design
  .github/workflows/book.yml
  README.md
  doc/book/.gitignore
  doc/book/book.toml
  doc/book/src/README.md
  doc/book/src/SUMMARY.md
  doc/book/src/design.md
  doc/book/src/design/chain-state.md
  doc/book/src/design/coins-view.md
  doc/book/src/doc/imgs/logo.png
  doc/book/src/doc/imgs/zcashd_screen.gif
Labels: A-documentation

#4967 cherry-pick upstream locking fixes
  src/addrman.h
  src/main.cpp
  src/main.h
  src/net.cpp
  src/net.h
Labels: C-upstream-port

#4963 Move the github API token out of updatecheck.py into an untracked file.
  .gitignore
  doc/release-process.md
  qa/zcash/updatecheck.py
Labels: safe-to-build

#4964 Update UniValue subtree
  src/rpc/misc.cpp
  src/univalue/.travis.yml
  src/univalue/README.md
  src/univalue/configure.ac
  src/univalue/include/univalue.h
  src/univalue/lib/univalue_get.cpp
  src/univalue/lib/univalue_read.cpp
  src/univalue/lib/univalue_write.cpp
  src/univalue/test/object.cpp
Labels: A-dependencies, C-upstream-port

#4966 Replace libzcashconsensus with libzcash_script
  .gitignore
  Makefile.am
  configure.ac
  libzcash_script.pc.in
  libzcashconsensus.pc.in
  src/Makefile.am
  src/Makefile.gtest.include
  src/Makefile.test.include
  src/script/zcash_script.cpp
  src/script/zcash_script.h
  src/test/script_tests.cpp
  zcutil/make-release.py
Labels: A-lib-script
