Repository zcash/zcash, pull requests merged in 2022-05, with the labels that each got.

#5918 ThreadStartWalletNotifier: wait until !IBD, rather than !reindex
  src/init.cpp
Labels: C-bug

#5905 Allow deprecated wallet features to be preemptively disabled.
  doc/book/src/SUMMARY.md
  doc/book/src/dev/deprecation.md
  doc/book/src/user/deprecation.md
  doc/release-notes.md
  qa/pull-tester/rpc-tests.py
  qa/rpc-tests/wallet_deprecation.py
  qa/rpc-tests/zcjoinsplit.py
  qa/rpc-tests/zcjoinsplitdoublespend.py
  src/bitcoind.cpp
  src/deprecation.cpp
  src/deprecation.h
  src/init.cpp
  src/util.cpp
  src/util.h
  src/wallet/rpcdump.cpp
  src/wallet/rpcwallet.cpp
Labels: S-committed, safe-to-build

#5410 Allow rpc python tests to be run standalone
  doc/release-notes.md
  qa/pull-tester/rpc-tests.py
  qa/rpc-tests/maxblocksinflight.py
  qa/rpc-tests/maxuploadtarget.py
  qa/rpc-tests/p2p-acceptblock.py
  qa/rpc-tests/test_framework/test_framework.py
  qa/rpc-tests/test_framework/util.py
Labels: A-testing, L-python, safe-to-build

#5883 Build releases from a commit hash, rather than a named branch.
  doc/hotfix-process.md
  doc/release-process.md
  zcutil/make-release.py
Labels: release

#5917 Select anchors at `-anchorconfirmations` depth.
  .cargo/config.offline
  Cargo.lock
  Cargo.toml
  contrib/debian/copyright
  doc/release-notes.md
  qa/rpc-tests/mempool_limit.py
  qa/rpc-tests/mempool_tx_expiry.py
  qa/rpc-tests/mergetoaddress_mixednotes.py
  qa/rpc-tests/mergetoaddress_sapling.py
  qa/rpc-tests/mergetoaddress_sprout.py
  qa/rpc-tests/regtest_signrawtransaction.py
  qa/rpc-tests/remove_sprout_shielding.py
  qa/rpc-tests/wallet_listreceived.py
  qa/rpc-tests/wallet_nullifiers.py
  qa/rpc-tests/wallet_orchard_persistence.py
  qa/rpc-tests/wallet_sendmany_any_taddr.py
  qa/rpc-tests/wallet_shieldingcoinbase.py
  qa/rpc-tests/wallet_treestate.py
  qa/rpc-tests/wallet_z_sendmany.py
  src/rust/include/rust/orchard/wallet.h
  src/rust/src/incremental_merkle_tree.rs
  src/rust/src/wallet.rs
  src/transaction_builder.cpp
  src/transaction_builder.h
  src/wallet/asyncrpcoperation_mergetoaddress.cpp
  src/wallet/asyncrpcoperation_saplingmigration.cpp
  src/wallet/asyncrpcoperation_sendmany.cpp
  src/wallet/asyncrpcoperation_sendmany.h
  src/wallet/gtest/test_orchard_wallet.cpp
  src/wallet/gtest/test_rpc_wallet.cpp
  src/wallet/gtest/test_wallet.cpp
  src/wallet/orchard.cpp
  src/wallet/orchard.h
  src/wallet/rpcwallet.cpp
  src/wallet/test/rpc_wallet_tests.cpp
  src/wallet/wallet.cpp
  src/wallet/wallet.h
Labels: safe-to-build

#5926 Add z_get(total)balance to deprecation flags.
  doc/book/src/user/deprecation.md
  doc/release-notes.md
  src/deprecation.cpp
  src/deprecation.h
  src/wallet/rpcwallet.cpp
Labels: A-wallet, A-rpc-interface

#5942 Deprecate legacy RPCs & update rpc docs to clarify which are transparent-only.
  doc/book/src/user/deprecation.md
  doc/release-notes.md
  src/deprecation.cpp
  src/deprecation.h
  src/wallet/rpcwallet.cpp
Labels: safe-to-build

#5943 Migrate to `zcash_primitives 0.6` et al
  .cargo/config.offline
  Cargo.lock
  Cargo.toml
Labels: A-dependencies, L-rust

#5944 Release v5.0.0
  README.md
  configure.ac
  contrib/debian/changelog
  contrib/gitian-descriptors/gitian-linux.yml
  doc/authors.md
  doc/man/zcash-cli.1
  doc/man/zcash-tx.1
  doc/man/zcashd-wallet-tool.1
  doc/man/zcashd.1
  doc/release-notes.md
  doc/release-notes/release-notes-5.0.0.md
  src/chainparams.cpp
  src/clientversion.h
  src/deprecation.h
  src/version.h
Labels: A-consensus, release, NU5

#5956 Ensure anchor depth is > 0 when selecting an Orchard anchor.
  .gitignore
  src/wallet/rpcwallet.cpp
Labels: safe-to-build

#5959 Improve thread names
  Cargo.lock
  Cargo.toml
  src/asyncrpcqueue.cpp
  src/bitcoind.cpp
  src/httpserver.cpp
  src/init.cpp
  src/main.cpp
  src/metrics.cpp
  src/rust/include/rust/init.h
  src/rust/src/init_ffi.rs
  src/rust/src/rustzcash.rs
  src/util.h
  src/wallet/walletdb.cpp
Labels: C-cleanup, usability, A-logging

#5057 Sync backports
  configure.ac
  src/Makefile.test.include
  src/bitcoin-tx.cpp
  src/dbwrapper.h
  src/httpserver.cpp
  src/init.cpp
  src/main.cpp
  src/main.h
  src/net.cpp
  src/net.h
  src/random.cpp
  src/rpc/mining.cpp
  src/sync.cpp
  src/sync.h
  src/test/key_tests.cpp
  src/test/script_tests.cpp
  src/test/sync_tests.cpp
  src/test/test_bitcoin.cpp
  src/threadsafety.h
  src/txmempool.h
  src/util.h
  src/wallet/test/wallet_tests.cpp
  src/wallet/wallet.cpp
  test/lint/lint-includes.sh
Labels: C-upstream-port, S-waiting-on-review, E-help-wanted, safe-to-build

#5963 Do not return Orchard components from z_gettreestate before NU5 activation.
  src/rpc/blockchain.cpp
Labels: I-performance, A-rpc-interface

#5965 Revert "Only return active protocol components from z_gettreestate."
  src/rpc/blockchain.cpp
Labels: safe-to-build

#5951 book: Add platform support information and tier policy
  doc/book/src/SUMMARY.md
  doc/book/src/dev/platform-tier-policy.md
  doc/book/src/user/platform-support.md
Labels: A-documentation, A-packaging, dev policy, A-CI, A-end-of-service
