Repository zcash/zcash, pull requests merged in 2022-10, with the labels that each got.

#6189 wallet: Remove lock on cs_main from CWallet::ChainTip
  src/wallet/wallet.cpp
Labels: A-wallet, I-performance, A-chain-sync, C-bugfix

#6191 test_framework: fix AttributeError in sapling_spends_compact_digest
  qa/rpc-tests/test_framework/zip244.py
Labels: A-testing

#6165 Fix display of binary name in error messages.
  qa/rpc-tests/test_framework/util.py
Labels: A-testing

#6204 Fix broken `zcashd --help`
  qa/pull-tester/rpc-tests.py
  qa/rpc-tests/show_help.py
  qa/rpc-tests/test_framework/util.py
  src/init.cpp
Labels: safe-to-build
