Repository zcash/zcash, pull requests merged in 2022-11, with the labels that each got.

#6238 Don't attempt to rewind the Orchard wallet to a height after its current checkpoint
  doc/release-notes.md
  src/wallet/wallet.cpp
Labels: I-fail-to-run

#6253 Fix `show_help` and `receivedby` RPC tests
  qa/rpc-tests/show_help.py
  qa/rpc-tests/test_framework/netutil.py
Labels: A-testing

#6255 fix aarch64 dependency native clang download URL
  depends/packages/native_clang.mk
Labels: A-build, A-dependencies, O-ARM

#6192 Reduce memory usage of CBlockIndex
  doc/release-notes.md
  qa/rpc-tests/test_framework/util.py
  src/chain.cpp
  src/chain.h
  src/main.cpp
  src/rest.cpp
  src/rpc/blockchain.cpp
  src/txdb.cpp
  src/txdb.h
Labels: memory management

#6266 Add release notes for #6122 (`asOfHeight` RPC parameters)
  doc/release-notes.md
Labels: release
