Repository zcash/zcash, pull requests merged in 2022-04, with the labels that each got.

#5775 Add Orchard support to z_listunspent.
  qa/rpc-tests/wallet_listnotes.py
  src/wallet/rpcwallet.cpp
Labels: S-committed

#5808 wallet: Treat `mnemonichdchain` records as key material
  src/wallet/walletdb.cpp
Labels: A-wallet, A-wallet-database

#5807 fix sporadic failures in WriteCryptedSaplingZkeyDirectToDb, StoreAndLoadSaplingZkeys, and in StoreAndRetrieveMnemonicSeedInEncryptedStore
  src/gtest/test_keystore.cpp
  src/wallet/gtest/test_wallet_zkeys.cpp
  src/zcash/address/mnemonic.h
Labels: safe-to-build

#5804 Apply HaveShieldedRequirements to coinbase transactions
  src/gtest/test_checktransaction.cpp
  src/main.cpp
  src/main.h
  src/test/transaction_tests.cpp
  src/txmempool.cpp
  src/utiltest.h
Labels: C-bug, I-SECURITY, A-consensus, I-protocol-fragility, safe-to-build, NU5, A-orchard

#5820 Release v4.6.0-2
  README.md
  configure.ac
  contrib/debian/changelog
  contrib/gitian-descriptors/gitian-linux.yml
  doc/authors.md
  doc/man/zcash-cli.1
  doc/man/zcash-tx.1
  doc/man/zcashd.1
  doc/release-notes/release-notes-4.6.0-2.md
  src/clientversion.h
  src/deprecation.h
Labels: release

#5809 wallet: Initialise ThreadNotifyWallets with wallets best block
  src/init.cpp
  src/validationinterface.cpp
  src/wallet/wallet.cpp
  src/wallet/wallet.h
Labels: C-bug, A-wallet, I-fail-to-run, A-chain-sync, safe-to-build, A-orchard

#5789 Fix a bug in initialization of the Orchard wallet after NU5 activation.
  Cargo.lock
  Cargo.toml
  qa/pull-tester/rpc-tests.py
  qa/rpc-tests/wallet_orchard_init.py
  src/rust/include/rust/orchard/wallet.h
  src/rust/src/wallet.rs
  src/validationinterface.cpp
  src/validationinterface.h
  src/wallet/gtest/test_wallet.cpp
  src/wallet/orchard.h
  src/wallet/wallet.cpp
  src/wallet/wallet.h
  src/zcash/IncrementalMerkleTree.hpp
  src/zcbenchmarks.cpp
Labels: C-bug, A-wallet, NU5

#5773 .gitignore: add files temporarily created by autoconf
  .gitignore
Labels: A-build, C-cleanup

#5828 Update Dockerfile
  contrib/docker/Dockerfile
Labels: A-build

#5824 Fix condition where change outputs could violate z_sendmany privacy policy.
  qa/pull-tester/rpc-tests.py
  qa/rpc-tests/turnstile.py
  qa/rpc-tests/wallet_unified_change.py
  src/miner.cpp
  src/wallet/asyncrpcoperation_sendmany.cpp
Labels: C-bug, A-wallet, I-privacy, A-wallet-change, safe-to-build

#5835 Update to orchard-0.1.0-beta.3, incrementalmerkletree 0.3.0-beta.2, secp256k1-0.21
  .cargo/config.offline
  Cargo.lock
  Cargo.toml
Labels: A-dependencies, L-rust

#5844 qa: Postpone update to Rust 1.60
  qa/zcash/postponed-updates.txt
Labels: A-dependencies

#5841 Add lints for Cargo patches
  .github/workflows/lints.yml
  test/lint/lint-cargo-patches.sh
Labels: A-CI

#5823 Add trace-level logging to the Orchard wallet
  src/rpc/server.cpp
  src/rust/src/wallet.rs
Labels: A-logging, L-rust, A-orchard

#5791 Add z_listaccounts API.
  qa/rpc-tests/wallet_accounts.py
  src/wallet/rpcwallet.cpp
Labels: A-wallet, A-rpc-interface, safe-to-build

#5793 test: Capture gtest log output and only print on error
  src/gtest/main.cpp
  src/rust/include/tracing.h
  src/rust/src/tracing_ffi.rs
Labels: A-testing, A-logging

#5849 Check for overflow in IncrementAccountCounter().
  src/wallet/wallet.cpp
  src/wallet/walletdb.h
Labels: safe-to-build

#5853 Ensure pindexPrev is not null before mining against it.
  src/miner.cpp
Labels: safe-to-build

#5852 Make Orchard finalState serialization format match Sapling.
  .cargo/config.offline
  Cargo.lock
  Cargo.toml
  qa/rpc-tests/finalsaplingroot.py
  src/rpc/blockchain.cpp
  src/rust/include/rust/orchard/incremental_merkle_tree.h
  src/rust/src/incremental_merkle_tree_ffi.rs
  src/zcash/IncrementalMerkleTree.hpp
Labels: A-rpc-interface, safe-to-build, A-orchard

#5855 Update dependencies for 4.7.0
  Cargo.lock
  Cargo.toml
  qa/zcash/updatecheck.py
Labels: A-dependencies

#5851 Change error message in getHeightRange
  src/rpc/misc.cpp
  src/test/rpc_tests.cpp
Labels: safe-to-build

#5861 add walletrequirebackup=false to the zcash argument list in smoke_tests.py
  qa/zcash/smoke_tests.py
Labels: safe-to-build

#5877 [4.7.0 release notes] testnet nodes that upgrade prior to height 1,842,420 still need to run with -reindex and -rescan
  doc/release-notes/release-notes-4.7.0.md
Labels: A-documentation, release

#5872 Fix typo in getaddressbalance RPC help
  src/rpc/misc.cpp
Labels: safe-to-build

#5871 zcutil/build.sh: Run zcutil/clean.sh before building
  doc/release-notes.md
  zcutil/build.sh
Labels: S-committed

#5870 Make -reindex and -reindex-chainstate imply -rescan
  doc/release-notes.md
  src/init.cpp
  src/wallet/wallet.cpp
Labels: A-wallet, A-chain-sync, S-committed

#5875 Update boost and native_b2 dependencies to version 1.79.0
  depends/packages/boost.mk
  doc/release-notes.md
  qa/zcash/postponed-updates.txt
Labels: S-committed

#5890 Fix typo
  src/wallet/wallet.cpp
Labels: safe-to-build

#5903 Closing #1539 simplifies gtest Makefile
  src/Makefile.gtest.include
Labels: safe-to-build

#5886 zcutil/build-debian-package.sh: copy executable and man page for zcashd-wallet-tool
  zcutil/build-debian-package.sh
Labels: A-packaging

#5881 Cargo.toml: Rename hdwallet source
  Cargo.lock
  Cargo.toml
Labels: A-build, L-rust, safe-to-build

#5815 Change the numbering convention for hotfixes
  doc/hotfix-process.md
  doc/release-process.md
  zcutil/make-release.py
Labels: A-build, release, L-python, S-committed

#5690 run btests in parallel
  src/Makefile.test.include
  src/test/Checkpoints_tests.cpp
  src/test/alert_tests.cpp
Labels: safe-to-build

#5908 Use bullseye apt source in Dockerfile to match debian:11 base image
  contrib/docker/Dockerfile
Labels: safe-to-pbuild

#5914 Document the block time in the `z_gettreestate` RPC response
  src/rpc/blockchain.cpp
Labels: safe-to-build

#5915 Update minimum chain work and set NU5 activation block hash for testnet
  src/chainparams.cpp
Labels: testnet, A-chain-sync

#5916 Specify the format and epoch for the block time in `z_gettreestate` RPC docs
  src/rpc/blockchain.cpp
Labels: safe-to-build
