Repository zcash/zcash, pull requests merged in 2022-06, with the labels that each got.

#5982 Revert "Switched sync.{cpp,h} to std threading primitives."
  src/sync.h
Labels: C-bug, C-upstream-port, A-networking

#5986 Note dependence on BOSL in COPYING
  COPYING
  contrib/debian/copyright
Labels: licensing

#5997 halo2 is now under MIT/Apache-2.0, so does not need a declaration in contrib/debian/copyright
  contrib/debian/copyright
Labels: licensing

#6003 Integrate cargo-vet into CI system
  .github/workflows/audits.yml
  Cargo.toml
  doc/book/src/dev/rust.md
  qa/supply-chain/audits.toml
  qa/supply-chain/config.toml
  qa/supply-chain/imports.lock
Labels: I-SECURITY, A-dependencies, L-rust

#6027 Update test scripts to support initial parallel RPCs
  qa/pull-tester/rpc-tests.py
Labels: I-performance, A-testing, A-rpc-interface, safe-to-build, safe-to-build-dev
