Repository zcash/zcash, pull requests merged in 2023-05, with the labels that each got.

#6628 Fix macOS build on CI
  src/rpc/client.h
  src/util/match.h
Labels: S-waiting-on-review

#6626 Centralize ReceiverType conversions
  src/Makefile.am
  src/Makefile.gtest.include
  src/gtest/test_util_string.cpp
  src/util/string.h
  src/wallet/rpcwallet.cpp
  src/zcash/address/unified.cpp
  src/zcash/address/unified.h
Labels: S-waiting-on-review

#6612 Encapsulate memos
  src/Makefile.am
  src/gtest/test_checktransaction.cpp
  src/gtest/test_joinsplit.cpp
  src/gtest/test_noteencryption.cpp
  src/gtest/test_transaction_builder.cpp
  src/miner.cpp
  src/rpc/server.cpp
  src/rpc/server.h
  src/transaction_builder.cpp
  src/transaction_builder.h
  src/wallet/asyncrpcoperation_mergetoaddress.h
  src/wallet/asyncrpcoperation_saplingmigration.cpp
  src/wallet/gtest/test_rpc_wallet.cpp
  src/wallet/memo.h
  src/wallet/orchard.h
  src/wallet/rpcdisclosure.cpp
  src/wallet/rpcwallet.cpp
  src/wallet/test/rpc_wallet_tests.cpp
  src/wallet/wallet.cpp
  src/wallet/wallet.h
  src/wallet/wallet_tx_builder.cpp
  src/wallet/wallet_tx_builder.h
  src/zcash/JoinSplit.hpp
  src/zcash/Note.cpp
  src/zcash/Note.hpp
  src/zcash/NoteEncryption.cpp
  src/zcash/NoteEncryption.hpp
  src/zcash/Zcash.h
  src/zcash/address/sapling.hpp
  src/zcash/memo.cpp
  src/zcash/memo.h
  src/zcbenchmarks.cpp
Labels: libzcash, C-cleanup, S-waiting-on-review, F-memo-field

#6492 Display pass ratio in RPC test summary
  qa/pull-tester/rpc-tests.py
Labels: S-waiting-on-review

#6634 Remove GitHub check for recent-enough branch
  .github/workflows/checks.yml
Labels: S-waiting-on-review, A-CI

#6635 Fix missing includes on macOS build
  src/zcash/memo.h
Labels: A-build, S-waiting-on-review, O-macos, C-bugfix

#6624 Enable & error on all un-violated warnings
  configure.ac
  src/Makefile.am
  src/Makefile.crc32c.include
  src/Makefile.leveldb.include
Labels: A-build, S-waiting-on-review

#6647 build: Fix `--with-libs` linking errors for MinGW cross-compilation
  src/Makefile.am
  src/Makefile.bench.include
  src/Makefile.gtest.include
  src/Makefile.test.include
Labels: A-build, O-windows, A-lib-script

#6639 Remove Ubuntu 18.04 as a supported platform
  contrib/devtools/symbol-check.py
  doc/book/src/user/platform-support.md
  doc/release-notes.md
Labels: A-documentation, O-linux

#6640 Add Ubuntu 22.04 as a Tier 3 platform
  .github/workflows/build.yml
  doc/book/src/user/platform-support.md
Labels: A-build, O-linux

#6637 Place Sapling components behind getters
  src/bench/verification.cpp
  src/coins.cpp
  src/gtest/test_checktransaction.cpp
  src/gtest/test_coins.cpp
  src/gtest/test_transaction_builder.cpp
  src/main.cpp
  src/miner.cpp
  src/primitives/transaction.cpp
  src/primitives/transaction.h
  src/rpc/rawtransaction.cpp
  src/script/interpreter.cpp
  src/test/coins_tests.cpp
  src/test/transaction_tests.cpp
  src/transaction_builder.cpp
  src/txmempool.cpp
  src/util/test.cpp
  src/wallet/gtest/test_orchard_wallet.cpp
  src/wallet/gtest/test_rpc_wallet.cpp
  src/wallet/gtest/test_wallet.cpp
  src/wallet/rpcwallet.cpp
  src/wallet/wallet.cpp
  src/zcbenchmarks.cpp
Labels: C-cleanup, P-sapling

#6653 Fix a minor bug in an error message
  src/wallet/asyncrpcoperation_common.cpp
Labels: A-wallet, S-waiting-on-review, A-rpc-interface, C-bugfix

#6662 Handle errors when getting change addr for account
  src/wallet/gtest/test_rpc_wallet.cpp
  src/wallet/wallet.cpp
  src/wallet/wallet.h
  src/wallet/wallet_tx_builder.cpp
Labels: A-wallet, A-rpc-interface, C-bugfix

#6660 Correct fee calculation for vin in tx creation
  qa/rpc-tests/mergetoaddress_helper.py
  qa/rpc-tests/wallet_shieldcoinbase.py
  src/wallet/gtest/test_rpc_wallet.cpp
  src/wallet/wallet_tx_builder.cpp
  src/wallet/wallet_tx_builder.h
Labels: A-wallet, A-rpc-interface, C-bugfix

#6668 Release v5.5.1
  README.md
  configure.ac
  contrib/debian/changelog
  contrib/gitian-descriptors/gitian-linux-parallel.yml
  contrib/gitian-descriptors/gitian-linux.yml
  doc/authors.md
  doc/book/src/user/release-support.md
  doc/man/zcash-cli.1
  doc/man/zcash-tx.1
  doc/man/zcashd-wallet-tool.1
  doc/man/zcashd.1
  doc/release-notes/release-notes-5.5.1.md
  qa/zcash/postponed-updates.txt
  src/clientversion.h
  src/deprecation.h
Labels: S-waiting-on-review, release

#6675 Make `./configure` quieter by default
  zcutil/build.sh
Labels: A-build

#6473 Share RPC param table between client and server
  qa/pull-tester/rpc-tests.py
  qa/rpc-tests/errors.py
  src/rpc/client.cpp
  src/rpc/common.h
  src/rpc/server.cpp
Labels: C-cleanup, A-rpc-interface

#6649 Add CCoinsView support for Orchard/Sapling subtrees.
  src/coins.cpp
  src/coins.h
  src/gtest/test_coins.cpp
  src/gtest/test_mempool.cpp
  src/gtest/test_transaction_builder.h
  src/gtest/test_validation.cpp
  src/test/coins_tests.cpp
  src/txdb.cpp
  src/txdb.h
  src/util/test.h
  src/zcash/IncrementalMerkleTree.hpp
  src/zcbenchmarks.cpp
Labels: A-wallet, S-waiting-on-review

#6684 Add golden tests for Orchard wallet state at the zcashd v5.6.0 boundary.
  qa/pull-tester/rpc-tests.py
  qa/rpc-tests/cache/golden-v5.6.0/cache_config.json
  qa/rpc-tests/cache/golden-v5.6.0/chain_cache.tar.gz
  qa/rpc-tests/cache/golden-v5.6.0/node0_wallet.tar.gz
  qa/rpc-tests/cache/golden-v5.6.0/node1_wallet.tar.gz
  qa/rpc-tests/cache/golden-v5.6.0/node2_wallet.tar.gz
  qa/rpc-tests/cache/golden-v5.6.0/node3_wallet.tar.gz
  qa/rpc-tests/test_framework/util.py
  qa/rpc-tests/wallet_golden_5_6_0.py
Labels: A-testing

#6689 Fix a nondeterministic error in wallet tests caused by output shuffling.
  src/wallet/gtest/test_wallet.cpp
Labels: A-testing, I-heisenbug
