Repository zcash/zcash, pull requests merged in 2023-02, with the labels that each got.

#6236 Adding tarfile member sanitization to extractall()
  qa/rpc-tests/upgrade_golden.py
Labels: I-SECURITY, A-testing, S-waiting-on-review

#6394 Patch zeromq to check the return value of snprintf where necessary.
  depends/packages/zeromq.mk
  depends/patches/zeromq/check_snprintf_return.patch
Labels: A-dependencies

#6176 Add a docker-compose.yml for prometheus/grafana metrics collection.
  contrib/metrics/docker-compose.yml
  contrib/metrics/grafana/dashboards/zcashd-metrics.json
  contrib/metrics/grafana/grafana.ini
  contrib/metrics/grafana/provisioning/dashboards/zcash.yaml
  contrib/metrics/grafana/provisioning/datasources/prometheus.yaml
  contrib/metrics/prometheus.yaml
  doc/book/src/user/metrics.md
Labels: S-waiting-on-review, S-scratching-an-itch, A-metrics, A-dev-tools

#6391 Release v5.4.0-rc4
  README.md
  configure.ac
  contrib/debian/changelog
  contrib/gitian-descriptors/gitian-linux-parallel.yml
  contrib/gitian-descriptors/gitian-linux.yml
  doc/man/zcash-cli.1
  doc/man/zcash-tx.1
  doc/man/zcashd-wallet-tool.1
  doc/man/zcashd.1
  doc/release-notes.md
  doc/release-notes/release-notes-5.4.0-rc4.md
  qa/zcash/postponed-updates.txt
  src/clientversion.h
  src/deprecation.h
Labels: release

#6313 Backport `BlockAssembler` class
  src/miner.cpp
  src/miner.h
  src/rpc/mining.cpp
  src/test/mempool_tests.cpp
  src/test/miner_tests.cpp
  src/test/test_bitcoin.cpp
  src/txmempool.h
Labels: C-upstream-port, A-block-creation

#6407 rust: Compile with ThinLTO
  Cargo.toml
Labels: I-performance, A-build, L-rust

#6406 Sleep for 200µs before each ActivateBestChainStep call
  src/main.cpp
Labels: A-wallet, I-regression, A-chain-sync, I-race

#6413 Release v5.4.0
  README.md
  configure.ac
  contrib/debian/changelog
  contrib/gitian-descriptors/gitian-linux-parallel.yml
  contrib/gitian-descriptors/gitian-linux.yml
  doc/authors.md
  doc/man/zcash-cli.1
  doc/man/zcash-tx.1
  doc/man/zcashd-wallet-tool.1
  doc/man/zcashd.1
  doc/release-notes.md
  doc/release-notes/release-notes-5.4.0.md
  src/clientversion.h
  src/deprecation.h
Labels: release

#6424 Sleep for 200µs before each `ActivateBestChainStep` call
  src/main.cpp
Labels: A-wallet, I-regression, A-chain-sync

#6399 Retroactively enable ZIP 216 before NU5 activation
  src/rust/include/librustzcash.h
  src/rust/src/rustzcash.rs
  src/rust/src/tests/key_agreement.rs
  src/rust/src/tests/notes.rs
  src/wallet/wallet.cpp
  src/zcash/Note.cpp
  src/zcash/Note.hpp
  src/zcash/NoteEncryption.cpp
  src/zcash/NoteEncryption.hpp
Labels: C-cleanup, A-consensus, NU5, P-sapling

#6423 Load `-allowdeprecated` settings after reading the config file
  qa/rpc-tests/wallet_deprecation.py
  src/bitcoind.cpp
  src/deprecation.cpp
  src/deprecation.h
Labels: C-bug, C-deprecation, C-bugfix

#6428 Release v5.4.1
  README.md
  configure.ac
  contrib/debian/changelog
  contrib/gitian-descriptors/gitian-linux-parallel.yml
  contrib/gitian-descriptors/gitian-linux.yml
  doc/authors.md
  doc/man/zcash-cli.1
  doc/man/zcash-tx.1
  doc/man/zcashd-wallet-tool.1
  doc/man/zcashd.1
  doc/release-notes/release-notes-5.4.1.md
  qa/zcash/postponed-updates.txt
  src/clientversion.h
  src/deprecation.h
Labels: release

#6417 Show in-progress tests when rpc-tests is interrupted
  qa/pull-tester/rpc-tests.py
Labels: A-testing, usability

#5244 Make all CCoinsView methods pure-virtual.
  src/bitcoin-tx.cpp
  src/coins.cpp
  src/coins.h
  src/gtest/test_coins.cpp
  src/gtest/test_history.cpp
  src/gtest/test_mempool.cpp
  src/gtest/test_transaction_builder.cpp
  src/gtest/test_transaction_builder.h
  src/gtest/test_validation.cpp
  src/init.cpp
  src/main.cpp
  src/rest.cpp
  src/rpc/rawtransaction.cpp
  src/test/coins_tests.cpp
  src/test/script_P2SH_tests.cpp
  src/test/transaction_tests.cpp
  src/txdb.h
  src/txmempool.h
  src/util/test.h
  src/wallet/gtest/test_orchard_wallet.cpp
  src/zcbenchmarks.cpp
Labels: C-cleanup, S-waiting-on-review, Death By A Thousand Cuts, S-scratching-an-itch

#6441 Migrate to LLVM 15
  .github/workflows/lints.yml
  Cargo.toml
  contrib/devtools/update-clang-hashes.sh
  depends/Makefile
  depends/packages/libcxx.mk
  depends/packages/native_clang.mk
  depends/packages/native_rust.mk
  qa/zcash/postponed-updates.txt
  rust-toolchain.toml
  src/rust/src/history_ffi.rs
  src/rust/src/incremental_merkle_tree.rs
  src/rust/src/metrics_ffi.rs
Labels: A-build, A-dependencies, L-rust, F-clang

#6443 Update dependencies for 5.5.0
  Cargo.lock
  Cargo.toml
  depends/funcs.mk
  depends/packages/native_cxxbridge.mk
  depends/packages/native_zstd.mk
  depends/patches/native_cxxbridge/Cargo.lock
  qa/supply-chain/audits.toml
  qa/supply-chain/config.toml
  qa/supply-chain/imports.lock
  qa/zcash/postponed-updates.txt
  qa/zcash/updatecheck.py
Labels: A-dependencies

#6445 Fix Horizen Security contact email
  SECURITY.md
Labels: I-SECURITY, A-documentation

#6434 Give better error messages if proof parameters aren't loaded
  src/rust/src/builder_ffi.rs
  src/rust/src/orchard_ffi.rs
  src/rust/src/rustzcash.rs
  src/rust/src/sapling.rs
Labels: I-error-handling

#6449 Update documentation link
  INSTALL
Labels: A-documentation

#6405 Clarify that patches to a dependency are under the same license as that dependency
  contrib/debian/copyright
Labels: S-waiting-on-review, licensing
