Repository zcash/zcash, pull requests merged in 2023-06, with the labels that each got.

#6692 Fix nondeterminism in `WalletTests.UpdatedSaplingNoteData`
  src/wallet/gtest/test_wallet.cpp
Labels: A-testing, I-heisenbug

#6549 Upgrade to the latest development incrementalmerkletree & bridgetree versions.
  .cargo/config.offline
  Cargo.lock
  Cargo.toml
  qa/supply-chain/audits.toml
  qa/supply-chain/config.toml
  qa/supply-chain/imports.lock
  src/rust/include/rust/orchard/wallet.h
  src/rust/src/incremental_merkle_tree.rs
  src/rust/src/merkle_frontier.rs
  src/rust/src/sapling.rs
  src/rust/src/wallet.rs
  src/wallet/gtest/test_orchard_wallet.cpp
  src/wallet/gtest/test_wallet.cpp
  src/wallet/orchard.cpp
  src/wallet/orchard.h
  src/wallet/wallet.cpp
  src/wallet/wallet.h
  src/wallet/wallet_tx_builder.cpp
Labels: A-wallet, A-dependencies, A-rust-ffi, A-wallet-database, A-orchard

#6691 Add Sapling complete subtrees to coins db
  src/coins.h
  src/init.cpp
  src/main.cpp
  src/uint256.h
  src/zcash/IncrementalMerkleTree.cpp
  src/zcash/IncrementalMerkleTree.hpp
Labels: A-rpc-interface, A-chain-sync, A-light-clients

#6467 Strengthen AllowRevealedSenders
  doc/release-notes.md
  qa/rpc-tests/mergetoaddress_helper.py
  qa/rpc-tests/wallet_sendmany_any_taddr.py
  qa/rpc-tests/wallet_shieldcoinbase.py
  qa/rpc-tests/wallet_z_sendmany.py
  src/wallet/asyncrpcoperation_common.cpp
  src/wallet/gtest/test_note_selection.cpp
  src/wallet/gtest/test_rpc_wallet.cpp
  src/wallet/test/wallet_tests.cpp
  src/wallet/wallet.cpp
  src/wallet/wallet.h
  src/wallet/wallet_tx_builder.cpp
Labels: A-wallet, I-privacy, S-waiting-on-review, A-rpc-interface

#6431 Add Orchard 2^16 subtree roots to the coins db.
  src/init.cpp
  src/main.cpp
  src/rust/src/bridge.rs
  src/rust/src/incremental_merkle_tree.rs
  src/rust/src/merkle_frontier.rs
  src/rust/src/wallet.rs
  src/zcash/IncrementalMerkleTree.hpp
Labels: A-consensus, A-rpc-interface, A-chain-sync, A-light-clients

#6677 RPC changes for fast spendability of notes in light client wallets
  qa/rpc-tests/finalorchardroot.py
  qa/rpc-tests/finalsaplingroot.py
  src/rpc/blockchain.cpp
  src/rpc/common.h
Labels: A-rpc-interface

#6699 Update to released versions of patch dependencies.
  .cargo/config.offline
  Cargo.lock
  Cargo.toml
  qa/supply-chain/audits.toml
  qa/supply-chain/config.toml
  qa/supply-chain/imports.lock
Labels: S-waiting-on-review, A-dependencies

#6694 Automatically migrate old coins database to account for complete subtrees for Sapling and Orchard
  qa/rpc-tests/finalorchardroot.py
  qa/rpc-tests/finalsaplingroot.py
  src/coins.cpp
  src/coins.h
  src/init.cpp
  src/main.cpp
  src/main.h
  src/rpc/blockchain.cpp
  test/lint/lint-includes.sh
Labels: S-waiting-on-review, A-chain-sync, A-light-clients

#6704 Version 5.6.0 update release notes
  doc/release-notes.md
  doc/release-process.md
  src/coins.cpp
Labels: A-documentation

#6703 contrib/debian/copyright: give more precise information for src/secp256k1
  contrib/debian/copyright
Labels: A-dependencies, licensing

#6705 Update ed25519-zebra dependency to 4.x
  Cargo.lock
  Cargo.toml
  qa/supply-chain/audits.toml
  qa/supply-chain/config.toml
  qa/supply-chain/imports.lock
Labels: A-dependencies

#6683 Update network upgrade golden tests for serialization to include nu5.
  qa/rpc-tests/golden/nu5.tar.gz
  qa/rpc-tests/upgrade_golden.py
Labels: A-testing

#6709 Revert native_rust upgrade
  depends/packages/native_rust.mk
  qa/zcash/postponed-updates.txt
Labels: A-dependencies

#6710 Add test for new IncrementalMerkleTree methods
  src/gtest/test_coins.cpp
  src/gtest/test_merkletree.cpp
  src/gtest/utils.cpp
  src/gtest/utils.h
Labels: A-testing

#6713 Release v5.6.0
  README.md
  configure.ac
  contrib/debian/changelog
  contrib/gitian-descriptors/gitian-linux-parallel.yml
  contrib/gitian-descriptors/gitian-linux.yml
  doc/authors.md
  doc/book/src/user/release-support.md
  doc/man/zcash-cli.1
  doc/man/zcash-tx.1
  doc/man/zcashd-wallet-tool.1
  doc/man/zcashd.1
  doc/release-notes.md
  doc/release-notes/release-notes-5.6.0.md
  src/clientversion.h
  src/deprecation.h
Labels: release

#6717 Update ed25519-zebra to 4.0.0.
  Cargo.lock
  Cargo.toml
  qa/supply-chain/audits.toml
  qa/supply-chain/config.toml
  qa/supply-chain/imports.lock
Labels: A-dependencies

#6714 Make a few small improvements to the release process doc.
  doc/release-process.md
Labels: A-documentation, release

#6720 CI: Add a lint that checks for headers missing from makefiles
  .github/workflows/lints.yml
  test/lint/lint-make-dist.sh
Labels: A-build, A-CI

#6701 wallet_listreceived.py: fix an assertion message and remove unnecessary use of LEGACY_DEFAULT_FEE
  qa/rpc-tests/wallet_listreceived.py
Labels: A-testing, C-cleanup

#6632 Add metrics for mempool composition
  contrib/metrics/grafana/dashboards/zcashd-metrics.json
  src/main.cpp
  src/txmempool.cpp
  src/txmempool.h
Labels: A-mempool, A-metrics

#6728 Restore `height` parameter as being optional in `getblocksubsidy` RPC calls.
  qa/rpc-tests/nuparams.py
  src/rpc/common.h
Labels: I-regression, A-rpc-interface

#6726 Fix broken Orchard note commitment tree parsing.
  qa/pull-tester/rpc-tests.py
  qa/rpc-tests/cache/golden-v5.6.0/cache_config.json
  qa/rpc-tests/cache/golden-v5.6.0/chain_cache.tar.gz
  qa/rpc-tests/cache/golden-v5.6.0/node0_wallet.tar.gz
  qa/rpc-tests/cache/golden-v5.6.0/node1_wallet.tar.gz
  qa/rpc-tests/cache/golden-v5.6.0/node2_wallet.tar.gz
  qa/rpc-tests/cache/golden-v5.6.0/node3_wallet.tar.gz
  qa/rpc-tests/cache/tarnished-v5.6.0/cache_config.json
  qa/rpc-tests/cache/tarnished-v5.6.0/chain_cache.tar.gz
  qa/rpc-tests/cache/tarnished-v5.6.0/node0_wallet.tar.gz
  qa/rpc-tests/cache/tarnished-v5.6.0/node1_wallet.tar.gz
  qa/rpc-tests/cache/tarnished-v5.6.0/node2_wallet.tar.gz
  qa/rpc-tests/cache/tarnished-v5.6.0/node3_wallet.tar.gz
  qa/rpc-tests/wallet_golden_5_6_0.py
  qa/rpc-tests/wallet_tarnished_5_6_0.py
  src/init.cpp
  src/rust/include/rust/orchard/wallet.h
  src/rust/src/incremental_merkle_tree.rs
  src/rust/src/wallet.rs
  src/wallet/orchard.h
  src/wallet/wallet.cpp
  src/wallet/walletdb.cpp
Labels: A-wallet, I-regression, I-fail-to-run

#6729 Release v5.6.1
  README.md
  configure.ac
  contrib/debian/changelog
  contrib/gitian-descriptors/gitian-linux-parallel.yml
  contrib/gitian-descriptors/gitian-linux.yml
  doc/authors.md
  doc/book/src/user/release-support.md
  doc/man/zcash-cli.1
  doc/man/zcash-tx.1
  doc/man/zcashd-wallet-tool.1
  doc/man/zcashd.1
  doc/release-notes/release-notes-5.6.1.md
  qa/zcash/postponed-updates.txt
  src/clientversion.h
  src/deprecation.h
Labels: release

#6724 Update ZCASH_SIGNING_KEY_ID in Dockerfile
  contrib/docker/Dockerfile
Labels: F-docker

#6734 test: Set `-limitdescendantcount` to match viable iteration limit
  qa/rpc-tests/mempool_packages.py
Labels: A-testing, I-heisenbug, C-bugfix

#6731 Update dependencies for 5.7.0
  .github/workflows/audits.yml
  Cargo.lock
  Cargo.toml
  contrib/debian/copyright
  deny.toml
  depends/packages/native_ccache.mk
  depends/packages/native_cxxbridge.mk
  depends/packages/tl_expected.mk
  depends/patches/native_cxxbridge/Cargo.lock
  depends/patches/tl_expected/remove-undefined-behaviour.diff
  qa/supply-chain/audits.toml
  qa/supply-chain/config.toml
  qa/supply-chain/imports.lock
  qa/zcash/postponed-updates.txt
Labels: A-dependencies

#6661 Deprecate fetch-params.sh and bundle Sapling parameters into zcashd
  Cargo.lock
  Cargo.toml
  doc/release-notes.md
  qa/supply-chain/audits.toml
  src/bench/bench_bitcoin.cpp
  src/gtest/utils.cpp
  src/init.cpp
  src/rust/include/librustzcash.h
  src/rust/src/rustzcash.rs
  src/rust/src/sprout-groth16.vk
  src/test/test_bitcoin.cpp
  zcutil/fetch-params.sh
Labels: A-crypto, A-consensus, zkSNARK Parameter Deployment, C-simplification, C-deprecation
