Repository zcash/zcash, pull requests merged in 2023-03, with the labels that each got.

#6452 New checkpoint at block 2000000 for mainnet
  src/chainparams.cpp
Labels: A-chain-sync

#6458 Make pool selection order more flexible
  src/wallet/wallet.cpp
Labels: S-waiting-on-review

#6464 book: Add page with release support details and EoS halt heights
  doc/book/src/SUMMARY.md
  doc/book/src/user/release-support.md
  zcutil/make-release.py
Labels: A-documentation, release, A-end-of-service

#6463 Simplify diversifier_index_t handling
  src/gtest/test_keystore.cpp
  src/keystore.cpp
  src/keystore.h
  src/wallet/wallet.cpp
Labels: A-wallet, C-cleanup

#6425 Add information about deprecated features to `deprecationinfo` results.
  doc/book/src/user/deprecation.md
  doc/release-notes.md
  qa/rpc-tests/wallet_deprecation.py
  src/deprecation.cpp
  src/deprecation.h
  src/rpc/net.cpp
Labels: S-waiting-on-review, A-rpc-interface, C-deprecation

#6465 depends: Update Rust to 1.68.0
  .github/workflows/lints.yml
  Cargo.toml
  depends/packages/native_rust.mk
  rust-toolchain.toml
Labels: A-dependencies, L-rust

#6469 qa: Update imported `cargo-vet` audit registries
  qa/supply-chain/config.toml
  qa/supply-chain/imports.lock
Labels: A-dependencies

#6479 Fix builds with `CONFIGURE_FLAGS=--disable-wallet`
  src/deprecation.cpp
  src/deprecation.h
  src/init.cpp
Labels: A-build, C-bugfix

#6476 Fix a couple of longstanding zcashd build warnings
  Makefile.am
  src/Makefile.am
Labels: A-build, C-cleanup

#6480 CI: Check that the PR branch has a sufficiently recent base for Tekton
  .github/workflows/checks.yml
Labels: A-CI

#6478 Fix `make distclean` to recursively remove `rust/gen`
  src/Makefile.am
Labels: A-build, C-bugfix

#6482 CI: Fix permissions for Checks workflow
  .github/workflows/checks.yml
Labels: A-CI, C-bugfix

#6460 Refactoring to split the weighted tx tree out of mempool_limit.{cpp,h} and make it more reusable
  src/Makefile.am
  src/Makefile.gtest.include
  src/gtest/test_mempoollimit.cpp
  src/gtest/test_weightedmap.cpp
  src/mempool_limit.cpp
  src/mempool_limit.h
  src/random.cpp
  src/random.h
  src/txmempool.cpp
  src/txmempool.h
  src/weighted_map.h
Labels: S-waiting-on-review

#6466 Improve CChainParams const correctness.
  src/chainparams.cpp
  src/chainparams.h
  src/deprecation.cpp
  src/deprecation.h
  src/gtest/test_deprecation.cpp
  src/main.cpp
Labels: C-cleanup, S-waiting-on-review, C-deprecation

#6487 CI: More fixes to "recent base" check
  .github/workflows/checks.yml
Labels: A-CI, C-bugfix

#6489 CI: Use `github.head_ref` instead of `HEAD` for "recent base" check
  .github/workflows/checks.yml
Labels: A-CI, C-bugfix

#6490 book: Add End-of-Support heights for v5.3.3 and v5.4.2
  doc/book/src/user/release-support.md
Labels: A-documentation, A-end-of-service

#6493 Update CI workflows
  .github/workflows/audits.yml
  .github/workflows/book.yml
  .github/workflows/checks.yml
  .github/workflows/lints.yml
  qa/supply-chain/config.toml
  qa/supply-chain/imports.lock
  rust-toolchain.toml
Labels: A-CI

#6459 Migrate to `zcash_primitives 0.10`
  Cargo.lock
  Cargo.toml
  qa/supply-chain/audits.toml
  src/gtest/test_checktransaction.cpp
  src/main.cpp
  src/rust/bin/inspect/transaction.rs
  src/rust/include/librustzcash.h
  src/rust/src/note_encryption.rs
  src/rust/src/rustzcash.rs
  src/rust/src/sapling.rs
  src/rust/src/tests/key_agreement.rs
  src/rust/src/tests/key_components.rs
  src/rust/src/transaction_ffi.rs
  src/rust/src/wallet_scanner.rs
  src/test/sighash_tests.cpp
  src/test/transaction_tests.cpp
  src/util/test.cpp
  src/util/test.h
  src/zcash/NoteEncryption.cpp
Labels: A-dependencies, L-rust, A-rust-ffi

#6499 Update dependencies again for 5.5.0
  Cargo.lock
  Cargo.toml
  depends/packages/native_cmake.mk
  depends/packages/native_cxxbridge.mk
  depends/patches/native_cxxbridge/Cargo.lock
  qa/supply-chain/audits.toml
  qa/supply-chain/config.toml
  qa/supply-chain/imports.lock
  qa/zcash/postponed-updates.txt
Labels: A-dependencies

#6377 Extract common transaction logic from z_sendmany
  doc/release-notes.md
  qa/rpc-tests/mempool_nu_activation.py
  qa/rpc-tests/remove_sprout_shielding.py
  qa/rpc-tests/wallet_sapling.py
  qa/rpc-tests/wallet_sendmany_any_taddr.py
  qa/rpc-tests/wallet_shieldingcoinbase.py
  qa/rpc-tests/wallet_z_sendmany.py
  src/Makefile.am
  src/init.cpp
  src/wallet/asyncrpcoperation_common.cpp
  src/wallet/asyncrpcoperation_common.h
  src/wallet/asyncrpcoperation_sendmany.cpp
  src/wallet/asyncrpcoperation_sendmany.h
  src/wallet/gtest/test_rpc_wallet.cpp
  src/wallet/rpcwallet.cpp
  src/wallet/test/rpc_wallet_tests.cpp
  src/wallet/wallet.cpp
  src/wallet/wallet.h
  src/wallet/wallet_tx_builder.cpp
  src/wallet/wallet_tx_builder.h
  src/zcash/Address.hpp
Labels: A-wallet, C-cleanup, S-waiting-on-review, A-rpc-interface

#6513 Fix current build errors
  qa/rpc-tests/show_help.py
  qa/rpc-tests/upgrade_golden.py
  src/gtest/test_checktransaction.cpp
  src/wallet/rpcwallet.cpp
Labels: C-bugfix

#6503 Remove CWallet member from WalletTxBuilder
  src/wallet/asyncrpcoperation_sendmany.cpp
  src/wallet/gtest/test_rpc_wallet.cpp
  src/wallet/rpcwallet.cpp
  src/wallet/test/rpc_wallet_tests.cpp
  src/wallet/wallet_tx_builder.cpp
  src/wallet/wallet_tx_builder.h
Labels: S-waiting-on-review

#6470 Improve taddr no-memo check.
  qa/rpc-tests/wallet_z_sendmany.py
  src/wallet/rpcwallet.cpp
  src/wallet/wallet_tx_builder.cpp
Labels: S-waiting-on-review

#6410 Refactor RPC privacyPolicy handling
  src/wallet/rpcwallet.cpp
Labels: S-waiting-on-review

#6352 Make RPC test output more deterministic
  qa/pull-tester/rpc-tests.py
Labels: S-waiting-on-review
