Repository zcash/zcash, pull requests merged in 2023-04, with the labels that each got.

#6408 Lock notes (except Orchard) in wallet_tx_builder
  src/wallet/asyncrpcoperation_sendmany.cpp
  src/wallet/asyncrpcoperation_sendmany.h
  src/wallet/wallet_tx_builder.cpp
  src/wallet/wallet_tx_builder.h
Labels: S-waiting-on-review

#6525 Correct EditorConfig for Makefiles
  .editorconfig
Labels: S-waiting-on-review

#6500 Update to use the `ff 0.13` dependency stack.
  .cargo/config.offline
  .github/workflows/audits.yml
  Cargo.lock
  Cargo.toml
  qa/supply-chain/audits.toml
  qa/supply-chain/config.toml
  qa/supply-chain/imports.lock
Labels: A-dependencies

#6526 Split C++ generated from Rust into own lib
  src/Makefile.am
  src/Makefile.bench.include
  src/Makefile.gtest.include
  src/Makefile.test.include
Labels: S-waiting-on-review

#6527 ZIP 317 preparation: fix bitrotted miner tests and add conventional fee computations
  src/Makefile.am
  src/crypto/equihash.cpp
  src/crypto/equihash.h
  src/miner.cpp
  src/pow/tromp/equi.h
  src/pow/tromp/equi_miner.h
  src/primitives/transaction.cpp
  src/primitives/transaction.h
  src/test/miner_tests.cpp
  src/zip317.cpp
  src/zip317.h
Labels: A-testing, F-tx-fees

#6494 Improve code readability using `examine` macro
  src/consensus/params.cpp
  src/key_io.cpp
  src/keystore.cpp
  src/miner.cpp
  src/transaction_builder.cpp
  src/util/match.h
  src/wallet/asyncrpcoperation_common.cpp
  src/wallet/asyncrpcoperation_mergetoaddress.cpp
  src/wallet/asyncrpcoperation_sendmany.cpp
  src/wallet/asyncrpcoperation_shieldcoinbase.cpp
  src/wallet/memo.h
  src/wallet/rpcdump.cpp
  src/wallet/rpcwallet.cpp
  src/wallet/wallet.cpp
  src/wallet/wallet_tx_builder.cpp
  src/wallet/wallet_tx_builder.h
  src/wallet/walletdb.h
  src/zcash/Address.cpp
  src/zcash/Address.hpp
  src/zcash/address/unified.cpp
Labels: C-cleanup, S-scratching-an-itch

#6531 Merge most `cxx::bridge` definitions into a single bridge
  src/Makefile.am
  src/bench/verification.cpp
  src/chainparams.h
  src/gtest/main.cpp
  src/gtest/test_checktransaction.cpp
  src/init.cpp
  src/main.h
  src/miner.cpp
  src/primitives/orchard.h
  src/rpc/rawtransaction.cpp
  src/rust/src/bridge.rs
  src/rust/src/bundlecache.rs
  src/rust/src/merkle_frontier.rs
  src/rust/src/note_encryption.rs
  src/rust/src/orchard_bundle.rs
  src/rust/src/rustzcash.rs
  src/rust/src/sapling.rs
  src/rust/src/wallet_scanner.rs
  src/test/test_bitcoin.cpp
  src/test/transaction_tests.cpp
  src/transaction_builder.h
  src/wallet/wallet.h
  src/zcash/IncrementalMerkleTree.hpp
  src/zcash/Note.hpp
  src/zcbenchmarks.cpp
Labels: C-cleanup, L-rust, A-rust-ffi

#6533 Expand `CppStream` to cover all `Stream`-like C++ types
  src/Makefile.am
  src/hash.h
  src/rust/src/bridge.rs
  src/rust/src/merkle_frontier.rs
  src/rust/src/streams.rs
  src/serialize.h
  src/streams.h
  src/streams_rust.cpp
  src/streams_rust.h
  src/zcash/IncrementalMerkleTree.hpp
Labels: C-cleanup, L-rust, A-rust-ffi

#6409 Require `AllowRevealedRecipients` for transparent change
  doc/release-notes.md
  qa/rpc-tests/regtest_signrawtransaction.py
  qa/rpc-tests/wallet_changeaddresses.py
  qa/rpc-tests/wallet_listreceived.py
  qa/rpc-tests/wallet_listunspent.py
  qa/rpc-tests/wallet_sendmany_any_taddr.py
  qa/rpc-tests/wallet_z_sendmany.py
  src/wallet/wallet_tx_builder.cpp
Labels: A-wallet, S-waiting-on-review

#6540 Correct the documentation of `-rpcconnect` in the example `zcash.conf`
  contrib/debian/examples/zcash.conf
  qa/rpc-tests/rpcbind_test.py
Labels: A-documentation, S-scratching-an-itch

#6535 build: Tolerate split LLVM versions
  depends/packages/libcxx.mk
  depends/packages/native_clang.mk
Labels: A-build, F-clang

#6538 use SOURCES_PATH instead of local git DEPENDS_SOURCES_DIR
  qa/zcash/test-depends-sources-mirror.py
Labels: dev infrastructure, A-dependencies, L-python, A-dev-tools

#6547 Fix `cargo vet`
  doc/book/src/dev/rust.md
  qa/supply-chain/audits.toml
  qa/supply-chain/config.toml
  qa/supply-chain/imports.lock
Labels: A-CI, A-dependencies, L-rust

#6545 Eliminate LegacyCompat–ZTXOSelector cycle
  qa/rpc-tests/mempool_nu_activation.py
  qa/rpc-tests/remove_sprout_shielding.py
  src/wallet/rpcwallet.cpp
Labels: S-waiting-on-review

#6548 Migrate to published `orchard 0.4`
  .cargo/config.offline
  Cargo.lock
  Cargo.toml
  qa/supply-chain/audits.toml
  qa/supply-chain/config.toml
  qa/supply-chain/imports.lock
Labels: A-dependencies, L-rust

#6448 Improve zcash-cli argument handling
  src/bitcoin-cli.cpp
  src/rpc/client.cpp
  src/rpc/client.h
  src/test/rpc_tests.cpp
  src/test/test_util.cpp
  src/wallet/rpcdisclosure.cpp
Labels: S-waiting-on-review

#6551 Update dependencies one more time for 5.5.0
  Cargo.lock
  Cargo.toml
  depends/packages/native_cmake.mk
  depends/packages/native_cxxbridge.mk
  depends/packages/native_rust.mk
  depends/packages/native_zstd.mk
  depends/patches/native_cxxbridge/Cargo.lock
  qa/supply-chain/audits.toml
  qa/supply-chain/config.toml
  qa/supply-chain/imports.lock
  qa/zcash/postponed-updates.txt
  qa/zcash/updatecheck.py
Labels: A-dependencies

#5993 rust: Migrate Ed25519 FFI to `cxx`
  src/Makefile.am
  src/bench/verification.cpp
  src/gtest/test_checktransaction.cpp
  src/gtest/test_consensus.cpp
  src/gtest/test_joinsplit.cpp
  src/gtest/test_transaction.cpp
  src/main.cpp
  src/primitives/transaction.cpp
  src/primitives/transaction.h
  src/proof_verifier.cpp
  src/proof_verifier.h
  src/rpc/rawtransaction.cpp
  src/rust/include/rust/ed25519.h
  src/rust/include/rust/ed25519/types.h
  src/rust/src/ed25519.rs
  src/serialize.h
  src/test/sighash_tests.cpp
  src/test/transaction_tests.cpp
  src/transaction_builder.cpp
  src/transaction_builder.h
  src/util/test.cpp
  src/wallet/asyncrpcoperation_mergetoaddress.cpp
  src/wallet/asyncrpcoperation_mergetoaddress.h
  src/wallet/asyncrpcoperation_sendmany.cpp
  src/wallet/asyncrpcoperation_sendmany.h
  src/wallet/asyncrpcoperation_shieldcoinbase.cpp
  src/wallet/asyncrpcoperation_shieldcoinbase.h
  src/wallet/gtest/test_paymentdisclosure.cpp
  src/wallet/paymentdisclosure.cpp
  src/wallet/paymentdisclosure.h
  src/wallet/rpcdisclosure.cpp
  src/wallet/rpcwallet.cpp
  src/zcash/JoinSplit.cpp
  src/zcash/JoinSplit.hpp
  src/zcbenchmarks.cpp
Labels: L-rust, A-rust-ffi

#6524 Support ZIP 317 fees in the zcashd wallet
  qa/rpc-tests/mempool_limit.py
  qa/rpc-tests/mempool_tx_expiry.py
  qa/rpc-tests/test_framework/zip317.py
  qa/rpc-tests/wallet_listreceived.py
  qa/rpc-tests/wallet_nullifiers.py
  qa/rpc-tests/wallet_parsing_amounts.py
  qa/rpc-tests/wallet_shieldingcoinbase.py
  qa/rpc-tests/wallet_treestate.py
  qa/rpc-tests/wallet_z_sendmany.py
  src/wallet/asyncrpcoperation_common.cpp
  src/wallet/asyncrpcoperation_sendmany.cpp
  src/wallet/asyncrpcoperation_sendmany.h
  src/wallet/gtest/test_rpc_wallet.cpp
  src/wallet/rpcwallet.cpp
  src/wallet/test/rpc_wallet_tests.cpp
  src/wallet/wallet_tx_builder.cpp
  src/wallet/wallet_tx_builder.h
  src/zip317.cpp
  src/zip317.h
Labels: A-wallet, S-waiting-on-review, F-tx-fees

#6558 Use published `zcash_primitives 0.11` and `zcash_proofs 0.11`
  .cargo/config.offline
  Cargo.lock
  Cargo.toml
  qa/supply-chain/audits.toml
  qa/supply-chain/config.toml
Labels: A-dependencies, L-rust

#6562 Fix zcash-cli crash when printing help message
  src/bitcoin-cli.cpp
  src/rpc/client.cpp
  src/test/rpc_tests.cpp
  src/wallet/test/rpc_wallet_tests.cpp
Labels: S-waiting-on-review

#6559 Use null as the ZIP 317 fee sentinel instead of -1
  qa/rpc-tests/test_framework/zip317.py
  qa/rpc-tests/wallet_shieldingcoinbase.py
  src/wallet/rpcwallet.cpp
Labels: A-wallet, S-waiting-on-review, A-rpc-interface

#6568 Have z_shieldcoinbase use WalletTxBuilder
  qa/rpc-tests/remove_sprout_shielding.py
  qa/rpc-tests/wallet_shieldcoinbase.py
  src/wallet/asyncrpcoperation_sendmany.cpp
  src/wallet/asyncrpcoperation_shieldcoinbase.cpp
  src/wallet/asyncrpcoperation_shieldcoinbase.h
  src/wallet/gtest/test_rpc_wallet.cpp
  src/wallet/rpcwallet.cpp
  src/wallet/test/rpc_wallet_tests.cpp
  src/wallet/wallet.cpp
  src/wallet/wallet.h
  src/wallet/wallet_tx_builder.cpp
Labels: S-waiting-on-review

#6574 Fix `mempool_packages` nondeterminism
  qa/rpc-tests/mempool_packages.py
Labels: C-bug, A-testing, I-race, C-bugfix

#6555 Support ZIP 317 fees for legacy wallet operations
  contrib/debian/examples/zcash.conf
  doc/man/zcashd.1
  doc/release-notes.md
  qa/rpc-tests/prioritisetransaction.py
  qa/rpc-tests/show_help.py
  qa/rpc-tests/wallet_shieldingcoinbase.py
  src/amount.cpp
  src/main.h
  src/util/moneystr.cpp
  src/util/moneystr.h
  src/wallet/asyncrpcoperation_common.cpp
  src/wallet/wallet.cpp
  src/wallet/wallet.h
  src/wallet/wallet_tx_builder.cpp
  src/wallet/wallet_tx_builder.h
Labels: A-wallet, A-wallet-change, F-tx-fees

#6576 WalletTxBuilder support for net payments
  qa/rpc-tests/wallet_shieldcoinbase.py
  src/wallet/asyncrpcoperation_shieldcoinbase.cpp
  src/wallet/asyncrpcoperation_shieldcoinbase.h
  src/wallet/rpcwallet.cpp
  src/wallet/wallet_tx_builder.cpp
  src/wallet/wallet_tx_builder.h
Labels: S-waiting-on-review

#6585 Final dependency update for 5.5.0
  Cargo.lock
  depends/packages/boost.mk
  qa/supply-chain/audits.toml
  qa/zcash/postponed-updates.txt
Labels: A-dependencies

#6403 Implement ZIP 317 block construction algorithm
  doc/release-notes.md
  qa/rpc-tests/mempool_packages.py
  qa/rpc-tests/mergetoaddress_helper.py
  qa/rpc-tests/mergetoaddress_sapling.py
  qa/rpc-tests/prioritisetransaction.py
  qa/rpc-tests/show_help.py
  qa/rpc-tests/test_framework/zip317.py
  qa/rpc-tests/wallet.py
  qa/rpc-tests/wallet_shieldingcoinbase.py
  src/Makefile.am
  src/init.cpp
  src/int128.h
  src/miner.cpp
  src/miner.h
  src/policy/policy.h
  src/random.cpp
  src/random.h
  src/test/addrman_tests.cpp
  src/test/miner_tests.cpp
  src/txmempool.cpp
  src/txmempool.h
  src/weighted_map.h
  src/zip317.h
Labels: F-tx-fees, A-block-creation

#6569 Have z_mergetoaddress use WalletTxBuilder
  doc/release-notes.md
  qa/rpc-tests/mergetoaddress_helper.py
  qa/rpc-tests/mergetoaddress_mixednotes.py
  qa/rpc-tests/mergetoaddress_sapling.py
  qa/rpc-tests/remove_sprout_shielding.py
  src/gtest/test_transaction_builder.cpp
  src/transaction_builder.cpp
  src/wallet/asyncrpcoperation_common.cpp
  src/wallet/asyncrpcoperation_mergetoaddress.cpp
  src/wallet/asyncrpcoperation_mergetoaddress.h
  src/wallet/asyncrpcoperation_shieldcoinbase.cpp
  src/wallet/gtest/test_rpc_wallet.cpp
  src/wallet/rpcwallet.cpp
  src/wallet/test/rpc_wallet_tests.cpp
  src/wallet/wallet_tx_builder.cpp
  src/wallet/wallet_tx_builder.h
Labels: A-wallet, A-rpc-interface

#6592 Release v5.5.0-rc1
  Cargo.toml
  README.md
  configure.ac
  contrib/debian/changelog
  contrib/gitian-descriptors/gitian-linux-parallel.yml
  contrib/gitian-descriptors/gitian-linux.yml
  depends/packages/native_rust.mk
  doc/authors.md
  doc/book/src/user/release-support.md
  doc/man/zcash-cli.1
  doc/man/zcash-tx.1
  doc/man/zcashd-wallet-tool.1
  doc/man/zcashd.1
  doc/release-notes/release-notes-5.5.0-rc1.md
  rust-toolchain.toml
  src/clientversion.h
  src/deprecation.h
Labels: release

#6597 Change module comment in bridge.rs to doc comment to fix errors in zcash_script build
  src/rust/src/bridge.rs
Labels: A-build

#6603 Allow explicit “no memo” in z_mergetoaddress
  qa/rpc-tests/mergetoaddress_helper.py
  qa/rpc-tests/mergetoaddress_sapling.py
  src/wallet/rpcwallet.cpp
  src/wallet/test/rpc_wallet_tests.cpp
  src/wallet/wallet_tx_builder.cpp
Labels: A-wallet, A-rpc-interface

#6598 Improve `-printpriority` output to log the modified fee, conventional fee, size, logical actions, and unpaid actions
  qa/rpc-tests/show_help.py
  src/init.cpp
  src/miner.cpp
Labels: A-logging, A-block-creation

#6607 Fix `--disable-mining` build regression
  src/init.cpp
  src/test/miner_tests.cpp
Labels: A-build, A-pow

#6571 CI: Add a GitHub Actions workflow that builds zcashd for platform tiers
  .github/workflows/build.yml
  depends/packages/bdb.mk
  depends/packages/native_clang.mk
  depends/packages/native_cxxbridge.mk
  depends/packages/rustcxx.mk
Labels: A-CI

#6606 Release v5.5.0-rc2
  README.md
  configure.ac
  contrib/debian/changelog
  contrib/gitian-descriptors/gitian-linux-parallel.yml
  contrib/gitian-descriptors/gitian-linux.yml
  doc/book/src/user/release-support.md
  doc/man/zcash-cli.1
  doc/man/zcash-tx.1
  doc/man/zcashd-wallet-tool.1
  doc/man/zcashd.1
  doc/release-notes.md
  doc/release-notes/release-notes-5.5.0-rc2.md
  src/clientversion.h
  src/compat.h
  src/deprecation.h
  src/init.cpp
  src/rust/src/bridge.rs
  src/script/zcash_script.cpp
  zcutil/make-release.py
Labels: release

#6615 Fix issues in zcash-cli
  src/rpc/client.cpp
  src/wallet/rpcwallet.cpp
Labels: S-waiting-on-review

#6617 Support nullable strings in `zcash-cli`
  src/rpc/client.cpp
  src/wallet/rpcwallet.cpp
Labels: S-waiting-on-review

#6618 Release v5.5.0 rc3
  README.md
  configure.ac
  contrib/debian/changelog
  contrib/gitian-descriptors/gitian-linux-parallel.yml
  contrib/gitian-descriptors/gitian-linux.yml
  doc/book/src/user/release-support.md
  doc/man/zcash-cli.1
  doc/man/zcash-tx.1
  doc/man/zcashd-wallet-tool.1
  doc/man/zcashd.1
  doc/release-notes/release-notes-5.5.0-rc3.md
  src/clientversion.h
  src/deprecation.h
Labels: release

#6591 Remove fee estimation and `estimatefee` RPC method
  doc/book/src/user/files.md
  doc/reduce-traffic.md
  doc/release-notes.md
  qa/pull-tester/rpc-tests.py
  qa/rpc-tests/feature_zip239.py
  qa/rpc-tests/getblocktemplate.py
  qa/rpc-tests/mempool_resurrect_test.py
  qa/rpc-tests/mempool_tx_expiry.py
  qa/rpc-tests/mergetoaddress_helper.py
  qa/rpc-tests/regtest_signrawtransaction.py
  qa/rpc-tests/show_help.py
  qa/rpc-tests/signrawtransaction_offline.py
  qa/rpc-tests/smartfees.py
  qa/rpc-tests/sprout_sapling_migration.py
  qa/rpc-tests/test_framework/util.py
  qa/rpc-tests/wallet_1941.py
  qa/rpc-tests/wallet_anchorfork.py
  qa/rpc-tests/wallet_listnotes.py
  qa/rpc-tests/wallet_listreceived.py
  qa/rpc-tests/wallet_nullifiers.py
  qa/rpc-tests/wallet_overwintertx.py
  qa/rpc-tests/wallet_sapling.py
  qa/rpc-tests/wallet_sendmany_any_taddr.py
  qa/rpc-tests/wallet_shieldcoinbase.py
  qa/rpc-tests/wallet_shieldingcoinbase.py
  qa/rpc-tests/wallet_treestate.py
  qa/rpc-tests/wallet_unified_change.py
  qa/rpc-tests/wallet_z_sendmany.py
  qa/rpc-tests/zkey_import_export.py
  qa/zcash/smoke_tests.py
  src/Makefile.am
  src/Makefile.test.include
  src/amount.cpp
  src/amount.h
  src/coins.cpp
  src/fuzzing/ReadFeeEstimates/fuzz.cpp
  src/fuzzing/ReadFeeEstimates/input/fee_estimates.dat
  src/gtest/test_mempool.cpp
  src/init.cpp
  src/main.cpp
  src/mempool_limit.h
  src/miner.cpp
  src/policy/fees.cpp
  src/policy/fees.h
  src/policy/policy.h
  src/rpc/client.cpp
  src/rpc/mining.cpp
  src/test/policyestimator_tests.cpp
  src/transaction_builder.h
  src/txmempool.cpp
  src/txmempool.h
  src/wallet/asyncrpcoperation_saplingmigration.cpp
  src/wallet/rpcwallet.h
  src/wallet/wallet.h
Labels: C-cleanup, C-simplification, D-bitcoin-divergence, F-tx-fees, C-tech-debt

#6619 Fix a false positive duplicate-#include lint
  src/compat.h
Labels: C-cleanup

#6616 Update `smoke_tests.py` to run against 5.5.0, using `allowdeprecated`
  qa/zcash/smoke_tests.py
Labels: A-testing

#6622 Release v5.5.0
  README.md
  configure.ac
  contrib/debian/changelog
  contrib/gitian-descriptors/gitian-linux-parallel.yml
  contrib/gitian-descriptors/gitian-linux.yml
  doc/authors.md
  doc/book/src/user/release-support.md
  doc/man/zcash-cli.1
  doc/man/zcash-tx.1
  doc/man/zcashd-wallet-tool.1
  doc/man/zcashd.1
  doc/release-notes.md
  doc/release-notes/release-notes-5.5.0.md
  src/clientversion.h
  src/deprecation.h
Labels: release

#6565 txdb: remove consistency checks
  src/txdb.cpp
Labels: I-performance
