Repository zcash/zcash, pull requests merged in 2023-12, with the labels that each got.

#6787 Suppress link warnings for unused command-line argument when building bdb
  depends/packages/bdb.mk
Labels: C-cleanup, A-dependencies

#6793 CI: Upload build artifacts and run unit tests
  .github/workflows/ci.yml
Labels: A-CI

#6794 CI: Add sharding to GoogleTest job
  .github/workflows/ci.yml
Labels: A-CI

#6798 Update dependencies for 5.8.0
  Cargo.lock
  Cargo.toml
  contrib/debian/copyright
  depends/packages/native_cmake.mk
  depends/packages/native_cxxbridge.mk
  depends/packages/utfcpp.mk
  depends/packages/zeromq.mk
  depends/patches/native_cxxbridge/Cargo.lock
  depends/patches/zeromq/check_snprintf_return.patch
  depends/patches/zeromq/stats_proxy-missing-braces.diff
  depends/patches/zeromq/use-snprintf-not-sprintf.patch
  depends/patches/zeromq/windows-unused-variables.diff
  qa/supply-chain/audits.toml
  qa/supply-chain/config.toml
  qa/supply-chain/imports.lock
  qa/zcash/postponed-updates.txt
Labels: A-dependencies

#6803 Release v5.8.0-rc1
  README.md
  configure.ac
  contrib/debian/changelog
  contrib/gitian-descriptors/gitian-linux-parallel.yml
  contrib/gitian-descriptors/gitian-linux.yml
  doc/book/src/user/release-support.md
  doc/man/zcash-cli.1
  doc/man/zcash-tx.1
  doc/man/zcashd-wallet-tool.1
  doc/man/zcashd.1
  doc/release-notes/release-notes-5.8.0-rc1.md
  src/clientversion.h
  src/deprecation.h
Labels: release
