Repository zcash/zcash, pull requests merged in 2023-09, with the labels that each got.

#6758 Update non-Rust dependencies for 5.7.0
  depends/packages/boost.mk
  depends/packages/libsodium.mk
  depends/packages/native_ccache.mk
  depends/packages/native_cmake.mk
  depends/packages/utfcpp.mk
  depends/patches/boost/6753-signals2-function-fix.patch
  qa/zcash/postponed-updates.txt
Labels: A-dependencies

#6759 Update Rust dependencies for 5.7.0
  Cargo.lock
  Cargo.toml
  depends/packages/native_cmake.mk
  depends/packages/native_cxxbridge.mk
  depends/patches/native_cxxbridge/Cargo.lock
  qa/supply-chain/audits.toml
  qa/supply-chain/config.toml
  qa/supply-chain/imports.lock
Labels: A-dependencies

#6765 Update more dependencies for 5.7.0
  Cargo.lock
  Cargo.toml
  depends/packages/native_cmake.mk
  qa/supply-chain/audits.toml
  qa/supply-chain/config.toml
  qa/supply-chain/imports.lock
  qa/zcash/postponed-updates.txt
Labels: A-dependencies

#6766 Remove CentOS 8 from CI builder files
  contrib/ci-builders/buildbot/Dockerfile-bbworker.centos8
  contrib/ci-builders/buildbot/Dockerfile-build.centos8
  contrib/ci-builders/buildbot/README.md
  contrib/ci-builders/buildbot/docker-build.sh
  contrib/ci-builders/tekton/Dockerfile-build.centos8
  contrib/ci-builders/tekton/README.md
  contrib/ci-builders/tekton/docker-build.sh
Labels: A-CI, C-deprecation

#6767 Updates getblockcount help message to the appropriate message.
  src/rpc/blockchain.cpp
Labels: A-documentation, A-rpc-interface

#6768 Release v5.7.0-rc1
  README.md
  configure.ac
  contrib/debian/changelog
  contrib/gitian-descriptors/gitian-linux-parallel.yml
  contrib/gitian-descriptors/gitian-linux.yml
  doc/book/src/user/release-support.md
  doc/man/zcash-cli.1
  doc/man/zcash-tx.1
  doc/man/zcashd-wallet-tool.1
  doc/man/zcashd.1
  doc/release-notes.md
  doc/release-notes/release-notes-5.7.0-rc1.md
  src/clientversion.h
  src/deprecation.h
Labels: release

#6769 Fix description of transaction weight ratio in v5.7.0 release notes.
  doc/release-notes.md
  doc/release-notes/release-notes-5.7.0-rc1.md
Labels: A-documentation

#6770 `utfcpp 3.2.5`
  depends/packages/utfcpp.mk
Labels: A-dependencies

#6771 Release v5.7.0
  README.md
  configure.ac
  contrib/debian/changelog
  contrib/gitian-descriptors/gitian-linux-parallel.yml
  contrib/gitian-descriptors/gitian-linux.yml
  doc/authors.md
  doc/book/src/user/release-support.md
  doc/man/zcash-cli.1
  doc/man/zcash-tx.1
  doc/man/zcashd-wallet-tool.1
  doc/man/zcashd.1
  doc/release-notes.md
  doc/release-notes/release-notes-5.7.0.md
  src/clientversion.h
  src/deprecation.h
Labels: release

#6774 CI: Use latest stable Rust for book deployment
  .github/workflows/book.yml
Labels: A-documentation, A-CI, C-bugfix
