Repository zcash/zcash, pull requests merged in 2024-09, with the labels that each got.

#6945 Rename ecc_addresses to bp_addresses in chainparams.cpp
  src/chainparams.cpp
Labels: C-cleanup

#6952 Update dependencies for 6.0.0
  Cargo.lock
  Cargo.toml
  depends/packages/native_cmake.mk
  depends/packages/native_cxxbridge.mk
  depends/packages/native_rust.mk
  depends/patches/native_cxxbridge/Cargo.lock
  qa/supply-chain/audits.toml
  qa/supply-chain/config.toml
  qa/supply-chain/imports.lock
  qa/zcash/postponed-updates.txt
  rust-toolchain.toml
  src/rust/bin/wallet_tool.rs
  src/rust/src/tests/zip339.rs
Labels: A-dependencies

#6953 Fix Windows build
  depends/packages/libcxx.mk
  depends/packages/libsodium.mk
  depends/patches/libsodium/1.0.20-immintrin-conflict.diff
Labels: A-build, O-windows
