Repository zcash/zcash, pull requests merged in 2024-08, with the labels that each got.

#6913 More maintenance for 5.10.0
  .github/workflows/ci.yml
  Cargo.lock
  Cargo.toml
  depends/packages/native_ccache.mk
  depends/packages/native_cmake.mk
  depends/packages/native_fmt.mk
  depends/packages/native_rust.mk
  doc/release-notes.md
  qa/supply-chain/config.toml
  qa/supply-chain/imports.lock
  qa/zcash/full_test_suite.py
  qa/zcash/postponed-updates.txt
  rust-toolchain.toml
  src/Makefile.am
  src/rust/bin/inspect/address.rs
  src/rust/bin/inspect/block.rs
  src/rust/bin/inspect/context.rs
  src/rust/bin/inspect/keys.rs
  src/rust/bin/inspect/main.rs
  src/rust/bin/inspect/transaction.rs
  src/rust/src/incremental_merkle_tree.rs
  src/rust/src/wallet.rs
Labels: A-dependencies

#6927 Backport fix for INV buffer blowup
  qa/rpc-tests/test_framework/comptool.py
  src/main.cpp
Labels: I-SECURITY

#6931 Update Python code to work, and avoid deprecation warnings, on Python 3.12
  qa/rpc-tests/getblocktemplate.py
  qa/rpc-tests/test_framework/authproxy.py
  qa/rpc-tests/test_framework/util.py
  qa/rpc-tests/upgrade_golden.py
  qa/rpc-tests/wallet_deprecation.py
  qa/rpc-tests/wallet_shieldingcoinbase.py
  qa/zcash/updatecheck.py
Labels: L-python

#6933 Implement "ZIP 236: Blocks must balance exactly" for NU6
  .github/workflows/ci.yml
  qa/README.md
  qa/rpc-tests/bip65-cltv-p2p.py
  qa/rpc-tests/bipdersig-p2p.py
  qa/rpc-tests/coinbase_funding_streams.py
  qa/rpc-tests/feature_zip239.py
  qa/rpc-tests/invalidblockrequest.py
  qa/rpc-tests/p2p-fullblocktest.py
  qa/rpc-tests/test_framework/blocktools.py
  qa/rpc-tests/test_framework/flyclient.py
  qa/rpc-tests/test_framework/mininode.py
  qa/rpc-tests/turnstile.py
  qa/rpc-tests/wallet_orchard_reindex.py
  qa/rpc-tests/zapwallettxes.py
  src/gtest/test_validation.cpp
  src/main.cpp
  src/miner.cpp
Labels: NU6

#6923 depends: Show the URLs from which dependencies are being downloaded
  depends/funcs.mk
Labels: A-dependencies

#6928 Backport fix for orphan handling
  qa/pull-tester/rpc-tests.py
  src/main.cpp
  src/main.h
  src/net.h
  src/test/DoS_tests.cpp
Labels: I-SECURITY

#6940 Change constant names for funding streams added in NU6 to match ZIP 214
  qa/rpc-tests/coinbase_funding_streams.py
  src/chainparams.cpp
  src/consensus/params.h
Labels: C-cleanup, A-consensus, NU6
