Repository zcash/zcash, pull requests merged in 2024-05, with the labels that each got.

#6877 Update CI with Github actions artifacts
  .github/actions/gcs-download-cloud-storage/action.yml
  .github/workflows/ci.yml
Labels: A-CI

#6879 Migrate to LLVM 18
  .cargo/config.toml.offline
  .gitignore
  Cargo.toml
  configure.ac
  contrib/devtools/update-clang-hashes.sh
  depends/packages/libcxx.mk
  depends/packages/libevent.mk
  depends/packages/libsodium.mk
  depends/packages/native_clang.mk
  depends/packages/native_libtinfo5.mk
  depends/packages/native_rust.mk
  depends/packages/packages.mk
  depends/patches/libsodium/1321-aarch64-fix-compiler-attributes.patch
  qa/zcash/postponed-updates.txt
  rust-toolchain.toml
  src/Makefile.am
  src/hash.h
  src/rust/bin/inspect/address.rs
  src/rust/bin/inspect/block.rs
  src/rust/bin/inspect/transaction.rs
  src/rust/src/metrics_ffi.rs
  src/rust/src/sprout.rs
  src/rust/src/tests/signatures.rs
  src/rust/src/wallet.rs
  src/wallet/gtest/test_wallet.cpp
  src/wallet/wallet.cpp
  zcutil/clean.sh
Labels: A-build, L-rust, F-clang

#6836 CI: Run RPC tests
  .github/workflows/ci.yml
  doc/book/src/user/platform-support.md
  qa/pull-tester/rpc-tests.py
Labels: A-CI

#6883 CI: Add separate status that encompasses required-pass status checks
  .github/workflows/ci-skip.yml
  .github/workflows/ci.yml
Labels: A-CI

#6884 CI: Give `statuses: write` permission to CI workflows
  .github/workflows/ci-skip.yml
  .github/workflows/ci.yml
Labels: A-CI

#6885 Update dependencies for 5.10.0
  Cargo.lock
  Cargo.toml
  depends/packages/native_cmake.mk
  depends/packages/native_cxxbridge.mk
  depends/patches/native_cxxbridge/Cargo.lock
  qa/supply-chain/audits.toml
  qa/supply-chain/config.toml
  qa/supply-chain/imports.lock
  qa/zcash/postponed-updates.txt
  qa/zcash/updatecheck.py
  src/rust/bin/inspect/context.rs
  src/rust/bin/inspect/keys.rs
  src/rust/bin/inspect/transaction.rs
  src/rust/src/note_encryption.rs
  src/rust/src/params.rs
  src/rust/src/sapling.rs
  src/rust/src/wallet_scanner.rs
Labels: A-dependencies

#6887 CI: Move required-pass checks behind a `workflow_run` event
  .github/workflows/ci-status.yml
  .github/workflows/ci.yml
Labels: A-CI

#6888 CI: Alter how RPC test venvs are cached to improve reliability
  .github/workflows/ci.yml
Labels: A-CI

#6889 CI: Alter `ci-skip.yml` to run in the context of the base of the PR
  .github/workflows/ci-skip.yml
Labels: A-CI

#6886 Fix a commit miscounting bug in `doc/authors.md`, and add some author aliases
  doc/authors.md
  zcutil/release-notes.py
Labels: A-documentation, C-cleanup, S-scratching-an-itch, A-dev-tools

#6891 Backport upstream bech32m implementation & implement `converttex` RPC method.
  doc/release-notes.md
  qa/pull-tester/rpc-tests.py
  qa/rpc-tests/converttex.py
  src/Makefile.am
  src/bech32.cpp
  src/bech32.h
  src/chainparams.cpp
  src/chainparams.h
  src/key_constants.h
  src/key_io.cpp
  src/key_io.h
  src/rpc/common.h
  src/test/bech32_tests.cpp
  src/util/vector.h
  src/wallet/rpcwallet.cpp
Labels: C-upstream-port, A-rpc-interface

#6896 Release v5.9.1
  README.md
  configure.ac
  contrib/debian/changelog
  contrib/gitian-descriptors/gitian-linux-parallel.yml
  contrib/gitian-descriptors/gitian-linux.yml
  doc/authors.md
  doc/book/src/user/release-support.md
  doc/man/zcash-cli.1
  doc/man/zcash-tx.1
  doc/man/zcashd-wallet-tool.1
  doc/man/zcashd.1
  doc/release-notes.md
  doc/release-notes/release-notes-5.9.1.md
  src/clientversion.h
  src/deprecation.h
Labels: C-release
