Repository zcash/zcash, pull requests merged in 2024-06, with the labels that each got.

#6880 chore: remove repetitive words
  qa/rpc-tests/test_framework/mininode.py
  src/rust/src/wallet.rs
  src/secp256k1/src/secp256k1.c
  src/test/merkle_tests.cpp
  src/txmempool.cpp
Labels: A-documentation

#6893 Deprecating buster
  .github/workflows/ci.yml
  contrib/gitian-descriptors/gitian-linux-parallel.yml
  contrib/gitian-descriptors/gitian-linux.yml
Labels: A-build, C-deprecation

#6905 CI: Migrate from `macos-11` runner to `macos-12` runner
  .github/workflows/ci.yml
Labels: A-CI, O-macos
