Repository zcash/zcash, pull requests merged in 2024-04, with the labels that each got.

#6784 rust: Migrate to latest revision of `zcash/librustzcash` crates
  .github/workflows/audits.yml
  Cargo.lock
  Cargo.toml
  qa/rpc-tests/finalorchardroot.py
  qa/rpc-tests/finalsaplingroot.py
  qa/supply-chain/audits.toml
  qa/supply-chain/config.toml
  qa/supply-chain/imports.lock
  src/gtest/test_checktransaction.cpp
  src/gtest/test_coins.cpp
  src/gtest/test_dynamicusage.cpp
  src/gtest/test_keys.cpp
  src/gtest/test_mempoollimit.cpp
  src/gtest/test_transaction_builder.cpp
  src/gtest/test_validation.cpp
  src/gtest/test_zip32.cpp
  src/gtest/utils.cpp
  src/miner.cpp
  src/rust/bin/inspect/context.rs
  src/rust/bin/inspect/keys.rs
  src/rust/bin/inspect/main.rs
  src/rust/bin/inspect/transaction.rs
  src/rust/include/rust/builder.h
  src/rust/src/address_ffi.rs
  src/rust/src/bridge.rs
  src/rust/src/builder_ffi.rs
  src/rust/src/incremental_merkle_tree.rs
  src/rust/src/init.rs
  src/rust/src/lib.rs
  src/rust/src/merkle_frontier.rs
  src/rust/src/note_encryption.rs
  src/rust/src/orchard_keys_ffi.rs
  src/rust/src/sapling.rs
  src/rust/src/sapling/spec.rs
  src/rust/src/sapling/zip32.rs
  src/rust/src/test_harness_ffi.rs
  src/rust/src/tests/key_components.rs
  src/rust/src/tests/mod.rs
  src/rust/src/tests/signatures.rs
  src/rust/src/transaction_ffi.rs
  src/rust/src/unified_keys_ffi.rs
  src/rust/src/wallet.rs
  src/rust/src/wallet_scanner.rs
  src/test/coins_tests.cpp
  src/test/key_tests.cpp
  src/transaction_builder.cpp
  src/transaction_builder.h
  src/util/test.cpp
  src/wallet/asyncrpcoperation_saplingmigration.cpp
  src/wallet/asyncrpcoperation_saplingmigration.h
  src/wallet/gtest/test_orchard_wallet.cpp
  src/wallet/gtest/test_rpc_wallet.cpp
  src/wallet/gtest/test_wallet.cpp
  src/wallet/gtest/test_wallet_zkeys.cpp
  src/wallet/test/rpc_wallet_tests.cpp
  src/wallet/wallet.cpp
  src/wallet/wallet_tx_builder.cpp
  src/zcash/address/zip32.cpp
  src/zcash/address/zip32.h
  src/zcbenchmarks.cpp
Labels: A-dependencies, L-rust

#6839 Update or postpone dependencies for zcashd 5.9.0
  depends/packages/native_ccache.mk
  depends/packages/native_cmake.mk
  qa/zcash/postponed-updates.txt
Labels: A-dependencies

#6800 Remove references to the BOSL license
  COPYING
  Cargo.toml
  contrib/debian/copyright
  deny.toml
  doc/release-notes.md
Labels: licensing

#6864 More dependency updates, postponements, and audits for 5.9.0
  Cargo.lock
  depends/packages/native_cmake.mk
  depends/packages/native_zstd.mk
  qa/supply-chain/audits.toml
  qa/supply-chain/config.toml
  qa/supply-chain/imports.lock
  qa/zcash/postponed-updates.txt
Labels: A-dependencies
